import React, { createContext, useContext, useState } from 'react';

const translations = {
  EN: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "Bureau of Indian Standards",
    home: "Home",
    aiAssistant: "AI Assistant",
    standards: "Standards",
    services: "Services",
    labs: "Lab Network",
    heroTitlePrefix: "Your Intelligent Guide to",
    heroTitleHighlight: "Indian Standards",
    heroSubtitle: "Ask a question. Find the right standard. Get source-backed guidance with instant statutory cross-referencing.",
    searchPlaceholder: "Ask anything about Indian Standards, ISI marks, or conformity...",
    searchButton: "Ask",
    standardsIndexed: "22,418 BIS Standards Indexed",
    qcoCompliance: "QCO Compliance Matrix v4.2",
    citationEngine: "Sub-Second Citation Engine",
    domainsTitle: "What can I help you with?",
    domainsSubtitle: "Select a vertical to initiate targeted compliance pipelines, test schedule lookup, or licensing audits.",
    viewCatalog: "Explore catalog",
    viewLicensing: "View licensing paths",
    searchLabs: "Search laboratories",
    verifyPurity: "Verify purity codes",
    allCategories: "All Categories",
    mandatoryQco: "Mandatory QCO Only",
    electronics: "Electronics (CRS)",
    consumerGoods: "Consumer Goods",
    foodAgri: "Food & Agriculture",
    launchAssistant: "Launch AI Assistant",
    activeSchemas: "21,400+ Active Standard Schemas",
    labsCount: "1,840 NABL & Assaying Labs"
  },
  HI: {
    title: "बीआईएस सिंक",
    govTag: "GOV.IN",
    subTag: "भारतीय मानक ब्यूरो",
    home: "होम",
    aiAssistant: "एआई सहायक",
    standards: "भारतीय मानक",
    services: "सेवाएं",
    labs: "प्रयोगशाला नेटवर्क",
    heroTitlePrefix: "भारतीय मानकों के लिए आपका",
    heroTitleHighlight: "स्मार्ट एआई गाइड",
    heroSubtitle: "सवाल पूछें। सही मानक खोजें। कानूनी संदर्भों के साथ प्रमाणित मार्गदर्शन प्राप्त करें।",
    searchPlaceholder: "भारतीय मानक, आईएसआई मार्क या प्रमाणन के बारे में पूछें...",
    searchButton: "खोजें",
    standardsIndexed: "२२,४१८ भारतीय मानक सूचीबद्ध",
    qcoCompliance: "क्यूसीओ अनुपालन मैट्रिक्स v4.2",
    citationEngine: "त्वरित कानूनी संदर्भ प्रणाली",
    domainsTitle: "हम आपकी क्या मदद कर सकते हैं?",
    domainsSubtitle: "अनुपालन, परीक्षण कार्यक्रम या लाइसेंसिंग के लिए उपयुक्त सेवा चुनें।",
    viewCatalog: "कैटलॉग देखें",
    viewLicensing: "लाइसेंसिंग प्रक्रिया देखें",
    searchLabs: "प्रयोगशालाएं खोजें",
    verifyPurity: "शुद्धता कोड सत्यापित करें",
    allCategories: "सभी श्रेणियां",
    mandatoryQco: "केवल अनिवार्य क्यूसीओ",
    electronics: "इलेक्ट्रॉनिक्स (सीआरएस)",
    consumerGoods: "उपभोक्ता उत्पाद",
    foodAgri: "खाद्य एवं कृषि",
    launchAssistant: "एआई सहायक शुरू करें",
    activeSchemas: "२१,४००+ सक्रिय मानक योजनाएं",
    labsCount: "१,८४० एनएबीएल व हॉलमार्किंग लैब्स"
  },
  TA: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "இந்திய தரநிலைகள் பணியகம்",
    home: "முகப்பு",
    aiAssistant: "AI உதவியாளர்",
    standards: "தரநிலைகள்",
    services: "சேவைகள்",
    labs: "ஆய்வகங்கள்",
    heroTitlePrefix: "இந்திய தரநிலைகளுக்கான உங்கள்",
    heroTitleHighlight: "அறிவுசார் வழிகாட்டி",
    heroSubtitle: "கேள்வி கேளுங்கள். சரியான தரநிலையைக் கண்டறியவும். சட்டபூர்வ வழிகாட்டுதலைப் பெறுங்கள்.",
    searchPlaceholder: "இந்திய தரநிலைகள் அல்லது ISI முத்திரை பற்றி கேளுங்கள்...",
    searchButton: "தேடு",
    standardsIndexed: "22,418 தரநிலைகள்",
    qcoCompliance: "QCO இணக்க மேட்ரிக்ஸ்",
    citationEngine: "விரைவு சான்று இயந்திரம்",
    domainsTitle: "நாங்கள் உங்களுக்கு எவ்வாறு உதவலாம்?",
    domainsSubtitle: "சான்றிதழ் மற்றும் ஆய்வக சேவைகளை எளிதாக கண்டறியவும்.",
    viewCatalog: "பட்டியலை காண்க",
    viewLicensing: "உரிம வழிகள்",
    searchLabs: "ஆய்வகங்களைத் தேடுங்கள்",
    verifyPurity: "ஹால்மார்க் சரிபார்க்கவும்",
    allCategories: "அனைத்து பிரிவுகள்",
    mandatoryQco: "கட்டாய QCO மட்டும்",
    electronics: "மின்னணுவியல் (CRS)",
    consumerGoods: "நுகர்வோர் பொருட்கள்",
    foodAgri: "உணவு மற்றும் விவசாயம்",
    launchAssistant: "AI உதவியாளரைத் தொடங்கவும்",
    activeSchemas: "21,400+ தரநிலை திட்டங்கள்",
    labsCount: "1,840 NABL ஆய்வகங்கள்"
  },
  TE: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "భారతీయ ప్రమాణాల బ్యూరో",
    home: "హోమ్",
    aiAssistant: "AI అసిస్టెంట్",
    standards: "ప్రమాణాలు",
    services: "సేవలు",
    labs: "ల్యాబ్ నెట్‌వర్క్",
    heroTitlePrefix: "భారతీయ ప్రమాణాల కోసం మీ",
    heroTitleHighlight: "ఇంటెలిజెంట్ గైడ్",
    heroSubtitle: "ప్రశ్న అడగండి. సరైన ప్రమాణాన్ని కనుగొనండి.",
    searchPlaceholder: "భారతీయ ప్రమాణాలు లేదా ISI మార్కుల గురించి అడగండి...",
    searchButton: "వెతకండి",
    standardsIndexed: "22,418 ప్రమాణాలు",
    qcoCompliance: "QCO మ్యాట్రిక్స్",
    citationEngine: "సైటేషన్ ఇంజిన్",
    domainsTitle: "మేము మీకు ఎలా సహాయం చేయవచ్చు?",
    domainsSubtitle: "లైసెన్సింగ్ మరియు టెస్టింగ్ సేవలను ఎంచుకోండి.",
    viewCatalog: "కేటలాగ్ చూడండి",
    viewLicensing: "లైసెన్సింగ్ మార్గాలు",
    searchLabs: "ల్యాబ్‌లను కనుగొనండి",
    verifyPurity: "స్వచ్ఛత కోడ్ ధృవీకరించండి",
    allCategories: "అన్ని వర్గాలు",
    mandatoryQco: "తప్పనిసరి QCO మాత్రమే",
    electronics: "ఎలక్ట్రానిక్స్ (CRS)",
    consumerGoods: "వినియోగదారు ఉత్పత్తులు",
    foodAgri: "ఆహారం & వ్యవసాయం",
    launchAssistant: "AI అసిస్టెంట్‌ని ప్రారంభించండి",
    activeSchemas: "21,400+ క్రియాశీల ప్రమాణాలు",
    labsCount: "1,840 NABL ల్యాబ్‌లు"
  },
  MR: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "भारतीय मानक ब्युरो",
    home: "मुख्यपृष्ठ",
    aiAssistant: "AI सहाय्यक",
    standards: "भारतीय मानके",
    services: "सेवा",
    labs: "प्रयोगशाळा नेटवर्क",
    heroTitlePrefix: "भारतीय मानकांसाठी आपले",
    heroTitleHighlight: "स्मार्ट AI मार्गदर्शक",
    heroSubtitle: "प्रश्न विचारा. योग्य मानक शोधा आणि अधिकृत मार्गदर्शन मिळवा.",
    searchPlaceholder: "भारतीय मानके किंवा ISI चिन्हांबद्दल विचारा...",
    searchButton: "शोधा",
    standardsIndexed: "२२,४१८ मानके",
    qcoCompliance: "QCO अनुपालन",
    citationEngine: "संदर्भ प्रणाली",
    domainsTitle: "आम्ही तुम्हाला कशी मदत करू शकतो?",
    domainsSubtitle: "प्रमाणीकरण आणि चाचणी सुविधांची माहिती मिळवा.",
    viewCatalog: "कॅटलॉग पहा",
    viewLicensing: "परवाना मार्ग",
    searchLabs: "प्रयोगशाळा शोधा",
    verifyPurity: "हॉलमार्क तपासा",
    allCategories: "सर्व श्रेणी",
    mandatoryQco: "केवळ अनिवार्य QCO",
    electronics: "इलेक्ट्रॉनिक्स (CRS)",
    consumerGoods: "ग्राहक उत्पादने",
    foodAgri: "अन्न आणि कृषी",
    launchAssistant: "AI सहाय्यक सुरू करा",
    activeSchemas: "२१,४००+ मानके",
    labsCount: "१,८४० लॅब्स"
  },
  BN: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস",
    home: "হোম",
    aiAssistant: "এআই সহকারী",
    standards: "মানকসমূহ",
    services: "সেবাসমূহ",
    labs: "ল্যাব নেটওয়ার্ক",
    heroTitlePrefix: "ভারতীয় মানের জন্য আপনার",
    heroTitleHighlight: "স্মার্ট নির্দেশিকা",
    heroSubtitle: "প্রশ্ন জিজ্ঞাসা করুন। সঠিক মানক খুঁজুন এবং নির্ভরযোগ্য তথ্য পান।",
    searchPlaceholder: "ভারতীয় মানক বা আইএসআই মার্ক সম্পর্কে জিজ্ঞাসা করুন...",
    searchButton: "অনুসন্ধান",
    standardsIndexed: "২২,৪১৮ মানক",
    qcoCompliance: "QCO সম্মতি",
    citationEngine: "সাইটেশন ইঞ্জিন",
    domainsTitle: "আমরা আপনাকে কীভাবে সাহায্য করতে পারি?",
    domainsSubtitle: "সার্টিফিকেশন ও পরীক্ষাগার পরিষেবা নির্বাচন করুন।",
    viewCatalog: "ক্যাটালগ দেখুন",
    viewLicensing: "লাইসেন্সিং প্রক্রিয়া",
    searchLabs: "পরীক্ষাগার খুঁজুন",
    verifyPurity: "বিশুদ্ধতা যাচাই করুন",
    allCategories: "সকল বিভাগ",
    mandatoryQco: "শুধুমাত্র বাধ্যতামূলক QCO",
    electronics: "ইলেকট্রনিক্স (CRS)",
    consumerGoods: "ভোগ্যপণ্য",
    foodAgri: "খাদ্য ও কৃষি",
    launchAssistant: "এআই সহকারী চালু করুন",
    activeSchemas: "২১,৪০০+ সক্রিয় স্কিমা",
    labsCount: "১,৮৪০ ল্যাব"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');
  const t = translations[lang] || translations.EN;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
