import React, { createContext, useContext, useState } from 'react';

const translations = {
  EN: {
    // Brand & General
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "Standards, Sync'd, Simplified",
    slogan: "National Standards AI Directive Engine",
    helpline: "National Statutory Standards Helpline: 1800-11-4000 (Toll Free) • IST 09:00 - 17:30",
    standardsLiveStatus: "BIS Standards Live Sync // 24.8 Repositories Active",

    // Navigation
    home: "Home",
    aiAssistant: "AI Assistant",
    standards: "Standards",
    services: "Services",
    labs: "Lab Network",
    signIn: "Sign In",
    signOut: "Sign Out",
    demoGuest: "Guest User",
    aiPoweredTag: "AI POWERED",

    // Hero Section
    heroTagline: "NATIONAL STANDARDS AI DIRECTIVE ENGINE // 24.8 REPOSITORIES ACTIVE",
    heroTitlePrefix: "Your Intelligent Guide to",
    heroTitleHighlight: "Indian Standards",
    heroSubtitle: "Ask a question. Find the right standard. Get source-backed guidance with instant statutory cross-referencing.",
    searchPlaceholder: "Ask anything about Indian Standards, ISI marks, or conformity...",
    searchButton: "Ask",
    ctrlK: "Ctrl K",
    standardsIndexed: "22,418 BIS Standards Indexed",
    qcoCompliance: "QCO Compliance Matrix v4.2",
    citationEngine: "Sub-Second Citation Engine",

    // Domains
    domainsTitle: "What can I help you with?",
    domainsSubtitle: "Select a vertical to initiate targeted compliance pipelines, test schedule lookup, or licensing audits.",
    viewCatalog: "Explore catalog",
    viewLicensing: "View licensing paths",
    searchLabs: "Search laboratories",
    verifyPurity: "Verify purity codes",

    // Real-Time Citation
    citationTag: "Real-Time Citation Stream",
    citationHeading: "Verified Direct Regulatory Passages",
    citationDesc: "Every AI response maps deterministically to exact clause numbers, mandatory gazette notifications, and laboratory sampling guidelines. Zero hallucination guaranteed through grounded RAG embeddings.",
    launchRagBtn: "Launch RAG Assistant Session",

    // National Quality Infrastructure
    infraTag: "NATIONAL QUALITY INFRASTRUCTURE",
    infraHeading: "Authoritative Certification & Laboratory Ecosystem",
    infraDesc: "Statutory quality assurance under the Bureau of Indian Standards Act, covering product safety, precision assaying, and accredited testing networks.",
    viewAllServicesBtn: "View All Conformity Services",

    // Workflow
    workflowTag: "METHODOLOGY",
    workflowTitle: "Workflow: Ask → Verify → Act",
    workflowDesc: "Precision engineering standards queries converted into statutory action paths in three deterministic phases.",
    step1Title: "Ask",
    step1Desc: "Submit natural language queries regarding products, HS codes, mandatory QCO lists, chemical composition tolerances, or test schedules.",
    step1Tag: "SEMANTIC EMBEDDING RETRIEVAL",
    step2Title: "Verify",
    step2Desc: "Inspect source-cited standard extracts, relevant amendments, statutory notifications from DPIIT/MoCA, and accredited testing lab lists.",
    step2Tag: "SOURCE CITATION VALIDATION",
    step3Title: "Act",
    step3Desc: "Generate Manakonline application checklists, initiate STI audits, book test slots at NABL labs, or verify 6-digit HUID authenticity tokens.",
    step3Tag: "REGULATORY ACTION ENGINE",

    // CTA
    ctaTitle: "Ready to consult the standards repository?",
    ctaDesc: "Deploy deep semantic search across the entire Indian Standards gazette with contextual regulatory guidance.",
    ctaAskBtn: "Ask the BIS Assistant",
    ctaExploreBtn: "Explore All 22,000+ Standards",

    // Standards Search Page
    standardsTitle: "Indian Standards Search",
    standardsSubtitle: "Verified regulatory guidelines, quality control orders (QCO), and technical specifications issued by the Bureau of Indian Standards.",
    standardsRepoTag: "NATIONAL STANDARDS REPOSITORY • 22,482 ACTIVE IS",
    schemeMandates: "SCHEME-I & QCO MANDATES",
    specMandatoryBannerTitle: "Standard Specifications & Mandatory Quality Orders",
    specMandatoryBannerDesc: "Clause-level compliance schemas, gazette notifications, and chemical/mechanical test criteria.",
    searchStandardsPlaceholder: "Search by IS number, product title, material or ICS code...",
    allCategories: "All Categories",
    mandatoryQco: "Mandatory QCO",
    electronics: "Electronics & IT",
    consumerGoods: "Consumer Goods",
    foodAgri: "Food & Agriculture",
    catalogResults: "Catalog Results",
    records: "Records",
    sortedBy: "Sorted by:",
    relevance: "Relevance",
    latestRevision: "Latest Revision",
    mandatoryFirst: "Mandatory First",
    viewStandard: "View Standard",
    gazetteVerified: "Gazette Verified",
    enforced: "Enforced:",
    askAiAboutStandard: "Ask AI regarding this standard",
    showing: "Showing",
    of: "of",
    standardsWord: "standards",
    allDisciplines: "All Technical Divisions",
    allStatuses: "All Statuses",
    qcoMandatoryOnly: "Mandatory QCO Only",
    resultsFound: "standards found",
    viewClauseSpec: "View Clause Spec",
    mandatoryQcoBadge: "MANDATORY QCO",
    voluntaryBadge: "VOLUNTARY",
    activeStatus: "ACTIVE",
    reaffirmedStatus: "REAFFIRMED",
    underRevisionStatus: "UNDER REVISION",

    // Services Page
    servicesTitle: "BIS Services",
    servicesSubtitle: "Clear, authoritative guidance on conformity assessment, testing, and consumer standards.",
    conformityFramework: "CONFORMITY & ASSURANCE FRAMEWORK",
    activeStandardSchemas: "Active Standard Schemas",
    nablAssayingLabs: "NABL & Assaying Labs",
    schemesMandatesBanner: "SCHEMES I - IV & CRS MANDATES",
    schemesBannerTitle: "Conformity Assessment & Product Certification Pathways",
    schemesBannerDesc: "Authoritative compliance procedures for ISI Mark, Hallmarking (HUID), CRS IT Registration, and FMCS for global imports.",
    module01Tag: "MODULE 01 // MANDATORY",
    module01Title: "Certification",
    module01Subtitle: "Understand BIS certification requirements.",
    module01Desc: "Explore Scheme-I (ISI Mark) and CRS schemes, step-by-step application walkthroughs, required factory audit documents, and fee structures.",
    exploreCertGuidance: "Explore Certification Guidance",
    module02Tag: "MODULE 02 // LAB NETWORK",
    module02Title: "Testing Laboratories",
    module02Subtitle: "Find relevant testing facilities.",
    module02Desc: "Search certified NABL and BIS laboratories across India by product standard, test scope, proximity, and estimated turnaround times.",
    locateLabsBtn: "Locate Testing Laboratories",
    interactiveRegistry: "Interactive Registry",
    geographicLabIndex: "Geographic Lab Index with Pin code lookup",
    module03Tag: "MODULE 03 // ASSAYING",
    module03Title: "Hallmarking",
    module03Subtitle: "Understand hallmarking requirements.",
    module03Desc: "Learn mandatory gold and silver hallmarking standards, 6-digit HUID authenticity checks, and how to register an assaying center.",
    viewHallmarkingRules: "View Hallmarking Rules",
    huidVerificationTitle: "6-Digit Alphanumeric Code Verification",
    verifyBtn: "Verify",
    module04Tag: "MODULE 04 // PUBLIC AUDIT",
    module04Title: "Consumer Help",
    module04Subtitle: "Get answers to common consumer questions.",
    module04Desc: "Verify certified ISI licenses on consumer goods, report substandard or fake certification marks, and file grievances with the BIS Consumer Affairs Department.",
    accessConsumerPortal: "Access Consumer Portal",
    licenseValidityStatus: "License Validity Status",
    instantVerification: "Instant Verification",
    spuriousMark: "Spurious Mark Escalation",
    priorityDispatch: "Priority Dispatch",
    autoStandardsRouting: "Automated Standards Routing",
    autoStandardsDesc: "Need personalized help choosing a service? Ask the BIS Assistant anytime for real-time standards routing and scheme matching.",
    launchAiAssistant: "Launch AI Assistant",

    // Lab Network Page
    labsTitle: "Accredited Testing Laboratories",
    labsSubtitle: "Find NABL-accredited & BIS-recognized testing laboratories for sample evaluation, batch testing, and conformity assessment.",
    geoIntel: "GEO-INTELLIGENCE // 1,840 ACCREDITED TESTING FACILITIES",
    statutoryTestingEco: "STATUTORY TESTING ECOSYSTEM",
    labBannerTitle: "National Laboratory & Conformity Testing Network",
    labBannerDesc: "ISO/IEC 17025 certified physical, chemical, metallurgical & microbiological analysis centers across India.",
    searchLabsPlaceholder: "Search lab by city, name, or standard tested (e.g. Mumbai, IS 17803)...",
    enterPincode: "Enter 6-digit PIN code...",
    allStandardsScope: "All Standards Scope",
    allStatesRegions: "All States & Regions",
    allStates: "All States / UTs",
    allAccreditations: "All Accreditations",
    accreditedScopes: "Accredited Testing Scopes",
    turnaround: "Turnaround:",
    bookSlotAi: "Book Slot via AI",
    nablIsoCert: "NABL ISO/IEC 17025 Certified",
    bookSlotBtn: "Book Testing Slot",
    viewLabDetailsBtn: "View Lab Profile",
    nablAccreditedBadge: "NABL ACCREDITED",

    // Standard Drawer & Modal
    icsTechnicalSchema: "ICS Technical Schema",
    enforcementDate: "Enforcement Date",
    regulatoryBody: "Regulatory Body",
    testingFacilities: "Testing Facilities",
    keyMandatoryClauses: "Key Mandatory Clauses & Test Protocols",
    applicableSchemeGuidance: "Applicable Scheme Guidance",
    viewFullGazetteNotice: "View Full Gazette Notice",
    consultAiAssistant: "Consult AI Assistant",

    // AI Assistant Page
    demoBannerPrefix: "Limited Demo Mode:",
    demoBannerSuffix: "demo queries remaining. Login for full statutory access and unlimited dossier exports.",
    loginToUnlock: "Login to Unlock",
    sessionTitle: "Standard Inquiry Session",
    strictMode: "Strict Mode",
    auditTrail: "Audit Trail",
    gazetteSynced: "Gazette Synced",
    applicableStandard: "Applicable National Standard",
    mandatoryProtocols: "Key Mandatory Test Protocols & Clauses",
    recommendedNextStep: "Recommended Next Step",
    copyResponse: "Copy Response",
    copied: "Copied",
    saveToDossier: "Save to Dossier",
    exportPdf: "Export PDF",
    helpfulPrompt: "Helpful?",
    askPlaceholder: "Ask a follow-up question regarding sample sizes, marking fee, or laboratory charges...",
    sendBtn: "Send",
    retrievingBtn: "Retrieving...",
    trySuggestions: "Try:",
    regulatorySources: "Regulatory Sources",
    citedCount: "Cited",
    viewFullGazettePdf: "View Full Gazette Notice (PDF)",

    // Telemetry
    telemetryTitle: "Compliance Matrix Telemetry",
    standardRisk: "Standard Risk",
    testingSpan: "Testing Span",
    passThreshold: "Pass Threshold",
    nablGrounded: "Grounded against NABL ISO/IEC 17025 test parameters",

    // Login Modal
    authGateway: "BIS DIRECTIVE AUTHENTICATION GATEWAY",
    loginHeading: "Wanna get started with BISync?",
    loginDesc: "Log in to unlock full statutory access, unbounded AI RAG queries, dossier exports, and laboratory slot booking.",
    selectStakeholder: "SELECT STAKEHOLDER PROFILE TO LOGIN:",
    preConfiguredDemo: "Pre-configured Demo Keys",
    loginAs: "Login as",

    // Footer
    bisActCompliant: "BIS Act 2016 Compliant",
    openSchemas: "Open Technical Schemas",
    integratedGov: "Integrated e-Governance",
    footerDesc: "Official statutory digital instrument compliant with Indian Standard regulations. Manak Bhavan, 9 Bahadur Shah Zafar Marg, New Delhi 110002.",
    statutoryDisclaimer: "Statutory Disclaimer",
    compliancePolicy: "Compliance Policy",
    auditRecords: "Audit Records"
  },

  HI: {
    // Brand & General
    title: "बीआईएस सिंक",
    govTag: "GOV.IN",
    subTag: "मानक, सिंक, सरल",
    slogan: "राष्ट्रीय मानक एआई निर्देशक प्रणाली",
    helpline: "राष्ट्रीय वैधानिक मानक हेल्पलाइन: 1800-11-4000 (टोल फ्री) • समय 09:00 - 17:30",
    standardsLiveStatus: "बीआईएस मानक लाइव सिंक // २४.८ रिपॉजिटरी सक्रिय",

    // Navigation
    home: "होम",
    aiAssistant: "एआई सहायक",
    standards: "मानक खोज",
    services: "सेवाएं",
    labs: "प्रयोगशाला नेटवर्क",
    signIn: "साइन इन",
    signOut: "साइन आउट",
    demoGuest: "अतिथि उपयोगकर्ता",
    aiPoweredTag: "एआई संचालित",

    // Hero Section
    heroTagline: "राष्ट्रीय मानक एआई निर्देशक प्रणाली // २४.८ रिपॉजिटरी सक्रिय",
    heroTitlePrefix: "भारतीय मानकों के लिए आपका",
    heroTitleHighlight: "स्मार्ट एआई गाइड",
    heroSubtitle: "सवाल पूछें। सही मानक खोजें। कानूनी संदर्भों और आधिकारिक राजपत्र के साथ प्रमाणित मार्गदर्शन प्राप्त करें।",
    searchPlaceholder: "भारतीय मानक, आईएसआई मार्क या प्रमाणन के बारे में पूछें...",
    searchButton: "खोजें",
    ctrlK: "Ctrl K",
    standardsIndexed: "२२,४१८ भारतीय मानक सूचीबद्ध",
    qcoCompliance: "क्यूसीओ अनुपालन मैट्रिक्स v4.2",
    citationEngine: "त्वरित कानूनी संदर्भ प्रणाली",

    // Domains
    domainsTitle: "हम आपकी क्या मदद कर सकते हैं?",
    domainsSubtitle: "अनुपालन, परीक्षण कार्यक्रम या लाइसेंसिंग के लिए उपयुक्त सेवा चुनें।",
    viewCatalog: "कैटलॉग देखें",
    viewLicensing: "लाइसेंसिंग प्रक्रिया देखें",
    searchLabs: "प्रयोगशालाएं खोजें",
    verifyPurity: "शुद्धता कोड सत्यापित करें",

    // Real-Time Citation
    citationTag: "रीयल-टाइम संदर्भ धारा",
    citationHeading: "सत्यापित प्रत्यक्ष कानूनी खंड",
    citationDesc: "प्रत्येक एआई उत्तर सीधे सटीक मानक खंडों, अनिवार्य राजपत्र अधिसूचनाओं और एनएबीएल परीक्षण प्रोटोकॉल से जुड़ा होता है।",
    launchRagBtn: "एआई सहायक सत्र शुरू करें",

    // National Quality Infrastructure
    infraTag: "राष्ट्रीय गुणवत्ता अवसंरचना",
    infraHeading: "आधिकारिक प्रमाणन और प्रयोगशाला नेटवर्क",
    infraDesc: "भारतीय मानक ब्यूरो अधिनियम के तहत उत्पाद सुरक्षा, शुद्धता प्रमाणीकरण और मान्यता प्राप्त प्रयोगशाला नेटवर्क।",
    viewAllServicesBtn: "सभी प्रमाणन सेवाएं देखें",

    // Workflow
    workflowTag: "कार्यप्रणाली",
    workflowTitle: "प्रक्रिया: पूछें → सत्यापित करें → कार्रवाई करें",
    workflowDesc: "इंजीनियरिंग मानकों के प्रश्नों को तीन चरणों में निश्चित वैधानिक कार्रवाई में बदला जाता है।",
    step1Title: "पूछें",
    step1Desc: "उत्पाद, एचएस कोड, अनिवार्य क्यूसीओ सूची, रासायनिक संरचना या परीक्षण कार्यक्रम से संबंधित प्रश्न पूछें।",
    step1Tag: "शब्दार्थ आधारित खोज",
    step2Title: "सत्यापित करें",
    step2Desc: "मानक उद्धरण, प्रासंगिक संशोधन, डीपीआईआईटी/मंत्रालय अधिसूचनाएं और प्रयोगशाला सूची की समीक्षा करें।",
    step2Tag: "संदर्भ सत्यापन",
    step3Title: "कार्रवाई करें",
    step3Desc: "मानकऑनलाइन चेकलिस्ट बनाएं, एसटीआई ऑडिट शुरू करें, एनएबीएल स्लॉट बुक करें या एचयूआईडी सत्यापित करें।",
    step3Tag: "वैधानिक कार्रवाई इंजन",

    // CTA
    ctaTitle: "क्या आप मानक रिपॉजिटरी से परामर्श के लिए तैयार हैं?",
    ctaDesc: "संपूर्ण भारतीय मानक राजपत्र पर प्रासंगिक कानूनी मार्गदर्शन के साथ गहरी खोज शुरू करें।",
    ctaAskBtn: "बीआईएस सहायक से पूछें",
    ctaExploreBtn: "सभी २२,०००+ मानक देखें",

    // Standards Search Page
    standardsTitle: "भारतीय मानक खोज",
    standardsSubtitle: "भारतीय मानक ब्यूरो द्वारा जारी सत्यापित नियामक दिशानिर्देश, गुणवत्ता नियंत्रण आदेश (QCO) और तकनीकी विनिर्देश।",
    standardsRepoTag: "राष्ट्रीय मानक रिपॉजिटरी • २२,४८२ सक्रिय मानक",
    schemeMandates: "योजना-I और क्यूसीओ अधिदेश",
    specMandatoryBannerTitle: "मानक विनिर्देश एवं अनिवार्य गुणवत्ता आदेश",
    specMandatoryBannerDesc: "खंड-स्तरीय अनुपालन स्कीमा, राजपत्र अधिसूचनाएं, और रासायनिक/यांत्रिक परीक्षण मानदंड।",
    searchStandardsPlaceholder: "आईएस नंबर, उत्पाद नाम, सामग्री या आईसीएस कोड द्वारा खोजें...",
    allCategories: "सभी श्रेणियां",
    mandatoryQco: "अनिवार्य क्यूसीओ",
    electronics: "इलेक्ट्रॉनिक्स एवं आईटी",
    consumerGoods: "उपभोक्ता उत्पाद",
    foodAgri: "खाद्य एवं कृषि",
    catalogResults: "कैटलॉग परिणाम",
    records: "रिकॉर्ड",
    sortedBy: "क्रमबद्ध करें:",
    relevance: "प्रासंगिकता",
    latestRevision: "नवीनतम संशोधन",
    mandatoryFirst: "अनिवार्य पहले",
    viewStandard: "मानक देखें",
    gazetteVerified: "राजपत्र सत्यापित",
    enforced: "लागू तिथि:",
    askAiAboutStandard: "इस मानक के बारे में एआई से पूछें",
    showing: "दिखाया जा रहा है",
    of: "कुल",
    standardsWord: "मानक",
    allDisciplines: "सभी तकनीकी प्रभाग",
    allStatuses: "सभी स्थितियां",
    qcoMandatoryOnly: "केवल अनिवार्य क्यूसीओ",
    resultsFound: "मानक उपलब्ध",
    viewClauseSpec: "खंड विनिर्देश देखें",
    mandatoryQcoBadge: "अनिवार्य क्यूसीओ",
    voluntaryBadge: "स्वैच्छिक",
    activeStatus: "सक्रिय",
    reaffirmedStatus: "पुनःपुष्ट",
    underRevisionStatus: "संशोधनाधीन",

    // Services Page
    servicesTitle: "बीआईएस सेवाएं",
    servicesSubtitle: "अनुरूपता मूल्यांकन, परीक्षण और उपभोक्ता मानकों पर स्पष्ट, आधिकारिक मार्गदर्शन।",
    conformityFramework: "अनुरूपता एवं आश्वासन ढांचा",
    activeStandardSchemas: "सक्रिय मानक स्कीमा",
    nablAssayingLabs: "एनएबीएल और परख प्रयोगशालाएं",
    schemesMandatesBanner: "योजनाएं I - IV एवं सीआरएस अधिदेश",
    schemesBannerTitle: "अनुरूपता मूल्यांकन एवं उत्पाद प्रमाणन मार्ग",
    schemesBannerDesc: "आईएसआई मार्क, हॉलमार्किंग (एचयूआईडी), सीआरएस आईटी पंजीकरण और एफएमसीएस के लिए वैधानिक अनुपालन प्रक्रियाएं।",
    module01Tag: "मॉड्यूल ०१ // अनिवार्य",
    module01Title: "प्रमाणन",
    module01Subtitle: "बीआईएस प्रमाणन आवश्यकताओं को समझें।",
    module01Desc: "योजना-I (आईएसआई मार्क) और सीआरएस योजनाओं, आवेदन प्रक्रिया, कारखाने के ऑडिट दस्तावेज़ों और शुल्क संरचना का अन्वेषण करें।",
    exploreCertGuidance: "प्रमाणन मार्गदर्शन देखें",
    module02Tag: "मॉड्यूल ०२ // प्रयोगशाला नेटवर्क",
    module02Title: "परीक्षण प्रयोगशालाएं",
    module02Subtitle: "प्रासंगिक परीक्षण सुविधाएं खोजें।",
    module02Desc: "उत्पाद मानक, परीक्षण क्षेत्र, निकटता और अनुमानित समय के आधार पर भारत भर में प्रमाणित एनएबीएल और बीआईएस प्रयोगशालाएं खोजें।",
    locateLabsBtn: "परीक्षण प्रयोगशालाएं खोजें",
    interactiveRegistry: "इंटरएक्टिव रजिस्ट्री",
    geographicLabIndex: "पिन कोड खोज के साथ भौगोलिक लैब सूचकांक",
    module03Tag: "मॉड्यूल ०३ // परख केंद्र",
    module03Title: "हॉलमार्किंग",
    module03Subtitle: "हॉलमार्किंग आवश्यकताओं को समझें।",
    module03Desc: "सोने और चांदी के अनिवार्य हॉलमार्किंग मानक, ६-अंकीय एचयूआईडी प्रामाणिकता जांच और परख केंद्र पंजीकरण प्रक्रिया जानें।",
    viewHallmarkingRules: "हॉलमार्किंग नियम देखें",
    huidVerificationTitle: "६-अंकीय अल्फ़ान्यूमेरिक कोड सत्यापन",
    verifyBtn: "सत्यापित करें",
    module04Tag: "मॉड्यूल ०४ // सार्वजनिक ऑडिट",
    module04Title: "उपभोक्ता सहायता",
    module04Subtitle: "सामान्य उपभोक्ता प्रश्नों के उत्तर प्राप्त करें।",
    module04Desc: "उपभोक्ता वस्तुओं पर आईएसआई लाइसेंस सत्यापित करें, घटिया या नकली चिह्नों की रिपोर्ट करें और बीआईएस उपभोक्ता मामलों के विभाग में शिकायत दर्ज करें।",
    accessConsumerPortal: "उपभोक्ता पोर्टल पर जाएं",
    licenseValidityStatus: "लाइसेंस वैधता स्थिति",
    instantVerification: "त्वरित सत्यापन",
    spuriousMark: "नकली चिह्न शिकायत",
    priorityDispatch: "प्राथमिकता निवारण",
    autoStandardsRouting: "स्वचालित मानक रूटिंग",
    autoStandardsDesc: "सेवा चुनने में व्यक्तिगत सहायता चाहिए? रीयल-टाइम मानक मिलान और योजना मार्गदर्शन के लिए कभी भी बीआईएस सहायक से पूछें।",
    launchAiAssistant: "एआई सहायक लॉन्च करें",

    // Lab Network Page
    labsTitle: "मान्यता प्राप्त परीक्षण प्रयोगशालाएं",
    labsSubtitle: "नमूना मूल्यांकन, बैच परीक्षण और अनुरूपता मूल्यांकन के लिए एनएबीएल-मान्यता प्राप्त और बीआईएस-मान्यता प्राप्त प्रयोगशालाएं खोजें।",
    geoIntel: "भू-स्थानिक बुद्धिमत्ता // १,८४० मान्यता प्राप्त परीक्षण सुविधाएं",
    statutoryTestingEco: "वैधानिक परीक्षण पारिस्थितिकी तंत्र",
    labBannerTitle: "राष्ट्रीय प्रयोगशाला एवं अनुरूपता परीक्षण नेटवर्क",
    labBannerDesc: "पूरे भारत में आईएसओ/आईईसी १७०२५ प्रमाणित भौतिक, रासायनिक, धातुकर्म और सूक्ष्मजैविक विश्लेषण केंद्र।",
    searchLabsPlaceholder: "शहर, नाम या मानक द्वारा लैब खोजें (उदा. मुंबई, IS 17803)...",
    enterPincode: "६-अंकीय पिन कोड दर्ज करें...",
    allStandardsScope: "सभी मानक क्षेत्र",
    allStatesRegions: "सभी राज्य एवं क्षेत्र",
    allStates: "सभी राज्य / केंद्र शासित प्रदेश",
    allAccreditations: "सभी मान्यताएं",
    accreditedScopes: "मान्यता प्राप्त परीक्षण क्षेत्र",
    turnaround: "परीक्षण अवधि:",
    bookSlotAi: "एआई द्वारा स्लॉट बुक करें",
    nablIsoCert: "एनएबीएल आईएसओ/आईईसी १७०२५ प्रमाणित",
    bookSlotBtn: "परीक्षण स्लॉट बुक करें",
    viewLabDetailsBtn: "प्रयोगशाला विवरण देखें",
    nablAccreditedBadge: "एनएबीएल मान्यता प्राप्त",

    // Standard Drawer & Modal
    icsTechnicalSchema: "आईसीएस तकनीकी स्कीमा",
    enforcementDate: "प्रवर्तन तिथि",
    regulatoryBody: "नियामक निकाय",
    testingFacilities: "परीक्षण सुविधाएं",
    keyMandatoryClauses: "प्रमुख अनिवार्य खंड एवं परीक्षण प्रोटोकॉल",
    applicableSchemeGuidance: "लागू योजना मार्गदर्शन",
    viewFullGazetteNotice: "पूर्ण राजपत्र सूचना देखें",
    consultAiAssistant: "एआई सहायक से परामर्श लें",

    // AI Assistant Page
    demoBannerPrefix: "सीमित डेमो मोड:",
    demoBannerSuffix: "डेमो प्रश्न शेष हैं। पूर्ण वैधानिक पहुंच और असीमित निर्यात के लिए लॉगिन करें।",
    loginToUnlock: "अनलॉक करने हेतु लॉगिन करें",
    sessionTitle: "मानक पूछताछ सत्र",
    strictMode: "सख्त मोड",
    auditTrail: "ऑडिट ट्रेल",
    gazetteSynced: "राजपत्र सिंक हुआ",
    applicableStandard: "लागू राष्ट्रीय मानक",
    mandatoryProtocols: "प्रमुख अनिवार्य परीक्षण प्रोटोकॉल एवं खंड",
    recommendedNextStep: "अनुशंसित अगला कदम",
    copyResponse: "उत्तर कॉपी करें",
    copied: "कॉपी हो गया",
    saveToDossier: "दस्तावेज़ में सहेजें",
    exportPdf: "पीडीएफ निर्यात करें",
    helpfulPrompt: "क्या यह मददगार था?",
    askPlaceholder: "नमूना आकार, अंकन शुल्क या प्रयोगशाला शुल्क के बारे में अनुवर्ती प्रश्न पूछें...",
    sendBtn: "भेजें",
    retrievingBtn: "प्राप्त कर रहा है...",
    trySuggestions: "सुझाव:",
    regulatorySources: "कानूनी स्रोत",
    citedCount: "उद्धृत",
    viewFullGazettePdf: "पूर्ण राजपत्र सूचना देखें (पीडीएफ)",

    // Telemetry
    telemetryTitle: "अनुपालन मैट्रिक्स टेलीमेट्री",
    standardRisk: "मानक जोखिम",
    testingSpan: "परीक्षण अवधि",
    passThreshold: "उत्तीर्ण सीमा",
    nablGrounded: "एनएबीएल आईएसओ/आईईसी १७०२५ मापदंडों पर आधारित",

    // Login Modal
    authGateway: "बीआईएस आधिकारिक प्रमाणीकरण गेटवे",
    loginHeading: "क्या आप बीआईएस सिंक शुरू करना चाहते हैं?",
    loginDesc: "पूर्ण वैधानिक पहुंच, असीमित एआई प्रश्न, डॉसियर निर्यात और लैब स्लॉट बुकिंग के लिए लॉगिन करें।",
    selectStakeholder: "लॉगिन के लिए हितधारक प्रोफाइल चुनें:",
    preConfiguredDemo: "पूर्व-कॉन्फ़िगर डेमो कुंजियाँ",
    loginAs: "के रूप में लॉगिन करें",

    // Footer
    bisActCompliant: "बीआईएस अधिनियम २०१६ अनुपालन",
    openSchemas: "ओपन तकनीकी स्कीमा",
    integratedGov: "एकीकृत ई-गवर्नेंस",
    footerDesc: "भारतीय मानक विनियमों के तहत आधिकारिक वैधानिक डिजिटल उपकरण। मानक भवन, ९ बहादुर शाह ज़फ़र मार्ग, नई दिल्ली ११०००२।",
    statutoryDisclaimer: "वैधानिक अस्वीकरण",
    compliancePolicy: "अनुपालन नीति",
    auditRecords: "ऑडिट रिकॉर्ड्स"
  },

  TA: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "தரநிலைகள், எளிமைப்படுத்தப்பட்டது",
    slogan: "தேசிய தரநிலைகள் AI வழிகாட்டி",
    helpline: "தேசிய சட்டப்பூர்வ தரநிலைகள் உதவி எண்: 1800-11-4000 • IST 09:00 - 17:30",
    standardsLiveStatus: "BIS தரநிலைகள் நேரலை இணைப்பு // 24.8 களஞ்சியங்கள்",

    home: "முகப்பு",
    aiAssistant: "AI உதவியாளர்",
    standards: "தரநிலைகள்",
    services: "சேவைகள்",
    labs: "ஆய்வக நெட்வொர்க்",
    signIn: "உள்நுழைக",
    signOut: "வெளியேறு",
    demoGuest: "விருந்தினர்",
    aiPoweredTag: "AI இயங்கும்",

    heroTagline: "தேசிய தரநிலைகள் AI வழிகாட்டி // 24.8 களஞ்சியங்கள் செயலில்",
    heroTitlePrefix: "இந்திய தரநிலைகளுக்கான உங்கள்",
    heroTitleHighlight: "அறிவுசார் AI வழிகாட்டி",
    heroSubtitle: "கேள்வி கேளுங்கள். சரியான தரநிலையைக் கண்டறியவும். சட்டபூர்வ வழிகாட்டுதலைப் பெறுங்கள்.",
    searchPlaceholder: "இந்திய தரநிலைகள் அல்லது ISI முத்திரை பற்றி கேளுங்கள்...",
    searchButton: "தேடு",
    ctrlK: "Ctrl K",
    standardsIndexed: "22,418 தரநிலைகள்",
    qcoCompliance: "QCO இணக்க மேட்ரிக்ஸ்",
    citationEngine: "விரைவு சான்று இயந்திரம்",

    domainsTitle: "நாங்கள் உங்களுக்கு எவ்வாறு உதவலாம்?",
    domainsSubtitle: "சான்றிதழ் மற்றும் ஆய்வக சேவைகளை எளிதாக கண்டறியவும்.",
    viewCatalog: "பட்டியலை காண்க",
    viewLicensing: "உரிம வழிகள்",
    searchLabs: "ஆய்வகங்களைத் தேடுங்கள்",
    verifyPurity: "ஹால்மார்க் சரிபார்க்கவும்",

    citationTag: "நேரலை சான்று ஓட்டம்",
    citationHeading: "சரிபார்க்கப்பட்ட ஒழுங்குமுறை பகுதிகள்",
    citationDesc: "ஒவ்வொரு AI பதிலும் துல்லியமான தரநிலை உட்பிரிவுகள் மற்றும் அரசிதழ் அறிவிப்புகளுடன் இணைக்கப்பட்டுள்ளது.",
    launchRagBtn: "AI அமர்வைத் தொடங்கவும்",

    infraTag: "தேசிய தர உள்கட்டமைப்பு",
    infraHeading: "அங்கீகரிக்கப்பட்ட சான்றிதழ் மற்றும் ஆய்வக சுற்றுச்சூழல்",
    infraDesc: "இந்திய தரநிலைகள் பணியக சட்டத்தின் கீழ் தயாரிப்பு பாதுகாப்பு மற்றும் ஆய்வக சோதனைகள்.",
    viewAllServicesBtn: "அனைத்து சேவைகளையும் காண்க",

    workflowTag: "முறை",
    workflowTitle: "செயல்முறை: கேள் → சரிபார் → செயல்படு",
    workflowDesc: "தரநிலை வினவல்கள் மூன்று படிகளில் துல்லியமான சட்டபூர்வ செயல்களாக மாற்றப்படுகின்றன.",
    step1Title: "கேள்",
    step1Desc: "தயாரிப்புகள், HS குறியீடுகள் அல்லது கட்டாய QCO பட்டியல்கள் பற்றி கேளுங்கள்.",
    step1Tag: "சொற்பொருள் தேடல்",
    step2Title: "சரிபார்",
    step2Desc: "தரநிலை மேற்கோள்கள் மற்றும் அங்கீகரிக்கப்பட்ட ஆய்வக பட்டியல்களைப் பார்க்கவும்.",
    step2Tag: "மேற்கோள் சரிபார்ப்பு",
    step3Title: "செயல்படு",
    step3Desc: "சரிபார்ப்புப் பட்டியலை உருவாக்கவும் அல்லது NABL ஆய்வக சோதனையை முன்பதிவு செய்யவும்.",
    step3Tag: "ஒழுங்குமுறை இயந்திரம்",

    ctaTitle: "தரநிலைகள் களஞ்சியத்தை அணுக தயாரா?",
    ctaDesc: "முழுமையான இந்திய தரநிலைகளில் விரிவான தேடலை மேற்கொள்ளுங்கள்.",
    ctaAskBtn: "BIS உதவியாளரிடம் கேளுங்கள்",
    ctaExploreBtn: "22,000+ தரநிலைகளை ஆராயுங்கள்",

    standardsTitle: "இந்திய தரநிலைகள் தேடல்",
    standardsSubtitle: "இந்திய தரநிலைகள் பணியகத்தால் வெளியிடப்பட்ட சரிபார்க்கப்பட்ட வழிகாட்டுதல்கள் மற்றும் விவரக்குறிப்புகள்.",
    standardsRepoTag: "தேசிய தரநிலைகள் களஞ்சியம் • 22,482 செயலில் உள்ள தரநிலைகள்",
    schemeMandates: "திட்டம்-I & கட்டாய QCO ஆணைகள்",
    specMandatoryBannerTitle: "தரநிலை விவரக்குறிப்புகள் மற்றும் கட்டாய தர உத்தரவுகள்",
    specMandatoryBannerDesc: "உட்பிரிவு அளவிலான இணக்க வரைபடங்கள், அரசிதழ் அறிவிப்புகள் மற்றும் சோதனை அளவுகோல்கள்.",
    searchStandardsPlaceholder: "IS எண், தயாரிப்பு பெயர் அல்லது ICS குறியீட்டின் மூலம் தேடுங்கள்...",
    allCategories: "அனைத்து பிரிவுகள்",
    mandatoryQco: "கட்டாய QCO",
    electronics: "மின்னணு & IT",
    consumerGoods: "நுகர்வோர் பொருட்கள்",
    foodAgri: "உணவு & விவசாயம்",
    catalogResults: "பட்டியல் முடிவுகள்",
    records: "பதிவுகள்",
    sortedBy: "வரிசைப்படுத்து:",
    relevance: "பொருத்தம்",
    latestRevision: "சமீபத்திய திருத்தம்",
    mandatoryFirst: "கட்டாய தரநிலைகள் முதலில்",
    viewStandard: "தரநிலையைக் காண்க",
    gazetteVerified: "அரசிதழ் சரிபார்க்கப்பட்டது",
    enforced: "நடைமுறைக்கு வந்த நாள்:",
    askAiAboutStandard: "இந்த தரநிலை பற்றி AI-யிடம் கேளுங்கள்",
    showing: "காட்டப்படுகிறது",
    of: "மொத்தம்",
    standardsWord: "தரநிலைகள்",
    allDisciplines: "அனைத்து துறைகள்",
    allStatuses: "அனைத்து நிலைகள்",
    qcoMandatoryOnly: "கட்டாய QCO மட்டும்",
    resultsFound: "தரநிலைகள் உள்ளன",
    viewClauseSpec: "விவரக்குறிப்பை காண்க",
    mandatoryQcoBadge: "கட்டாய QCO",
    voluntaryBadge: "விருப்பப்படி",
    activeStatus: "செயலில்",
    reaffirmedStatus: "மீண்டும் உறுதிப்படுத்தப்பட்டது",
    underRevisionStatus: "மறுபரிசீலனையில்",

    servicesTitle: "BIS சேவைகள்",
    servicesSubtitle: "சான்றிதழ் மற்றும் ஆய்வக சேவைகள் பற்றிய அதிகாரப்பூர்வ வழிகாட்டுதல்.",
    conformityFramework: "இணக்கம் & உத்தரவாத கட்டமைப்பு",
    activeStandardSchemas: "செயலில் உள்ள திட்டங்கள்",
    nablAssayingLabs: "NABL & மதிப்பீட்டு ஆய்வகங்கள்",
    schemesMandatesBanner: "திட்டங்கள் I - IV & CRS ஆணைகள்",
    schemesBannerTitle: "தயாரிப்பு சான்றிதழ் மற்றும் இணக்க வழிகள்",
    schemesBannerDesc: "ISI முத்திரை, ஹால்மார்க்கிங் (HUID), CRS IT பதிவுக்கான அதிகாரப்பூர்வ நடைமுறைகள்.",
    module01Tag: "தொகுதி 01 // கட்டாயமானது",
    module01Title: "சான்றிதழ்",
    module01Subtitle: "BIS சான்றிதழ் தேவைகளைப் புரிந்து கொள்ளுங்கள்.",
    module01Desc: "திட்டம்-I (ISI முத்திரை) மற்றும் CRS திட்டங்கள், கட்டண அமைப்புகளை ஆராயுங்கள்.",
    exploreCertGuidance: "சான்றிதழ் வழிகாட்டுதல்",
    module02Tag: "தொகுதி 02 // ஆய்வக நெட்வொர்க்",
    module02Title: "சோதனை ஆய்வகங்கள்",
    module02Subtitle: "பொருத்தமான சோதனை வசதிகளைக் கண்டறியவும்.",
    module02Desc: "தயாரிப்பு தரநிலை மற்றும் இருப்பிடம் அடிப்படையில் NABL மற்றும் BIS ஆய்வகங்களைத் தேடுங்கள்.",
    locateLabsBtn: "ஆய்வகங்களைக் கண்டறியவும்",
    interactiveRegistry: "ஊடாடும் பதிவேடு",
    geographicLabIndex: "பின் குறியீட்டுடன் புவியியல் ஆய்வக அட்டவணை",
    module03Tag: "தொகுதி 03 // மதிப்பீடு",
    module03Title: "ஹால்மார்க்கிங்",
    module03Subtitle: "ஹால்மார்க்கிங் விதிகளை அறிந்து கொள்ளுங்கள்.",
    module03Desc: "தங்க நகைகளுக்கான 6 இலக்க HUID நம்பகத்தன்மை சோதனைகள் பற்றி அறியவும்.",
    viewHallmarkingRules: "ஹால்மார்க்கிங் விதிகள்",
    huidVerificationTitle: "6 இலக்க குறியீடு சரிபார்ப்பு",
    verifyBtn: "சரிபார்க்கவும்",
    module04Tag: "தொகுதி 04 // பொது தணிக்கை",
    module04Title: "நுகர்வோர் உதவி",
    module04Subtitle: "பொதுவான நுகர்வோர் கேள்விகளுக்கு விடை காணுங்கள்.",
    module04Desc: "ISI உரிமங்களை சரிபார்க்கவும் மற்றும் போலி முத்திரைகள் மீது புகார் அளிக்கவும்.",
    accessConsumerPortal: "நுகர்வோர் போர்டல்",
    licenseValidityStatus: "உரிம நிலை",
    instantVerification: "உடனடி சரிபார்ப்பு",
    spuriousMark: "போலி முத்திரை புகார்",
    priorityDispatch: "முன்னுரிமை நடவடிக்கை",
    autoStandardsRouting: "தானியங்கி தரநிலை வழிகாட்டுதல்",
    autoStandardsDesc: "சேவையைத் தேர்ந்தெடுக்க உதவி தேவையா? BIS உதவியாளரிடம் கேட்கவும்.",
    launchAiAssistant: "AI உதவியாளரைத் தொடங்குங்கள்",

    labsTitle: "அங்கீகரிக்கப்பட்ட சோதனை ஆய்வகங்கள்",
    labsSubtitle: "NABL மற்றும் BIS அங்கீகாரம் பெற்ற சோதனை ஆய்வகங்களை கண்டறியவும்.",
    geoIntel: "புவியியல் தகவல் // 1,840 அங்கீகரிக்கப்பட்ட ஆய்வகங்கள்",
    statutoryTestingEco: "சட்டப்பூர்வ சோதனை சுற்றுச்சூழல்",
    labBannerTitle: "தேசிய ஆய்வக மற்றும் சோதனை நெட்வொர்க்",
    labBannerDesc: "இந்தியா முழுவதும் உள்ள ISO/IEC 17025 சான்றளிக்கப்பட்ட ஆய்வகங்கள்.",
    searchLabsPlaceholder: "நகரம், பெயர் அல்லது தரநிலை கொண்டு தேடுங்கள்...",
    enterPincode: "6 இலக்க பின் குறியீட்டை உள்ளிடவும்...",
    allStandardsScope: "அனைத்து தரநிலை எல்லைகள்",
    allStatesRegions: "அனைத்து மாநிலங்கள் & பகுதிகள்",
    allStates: "அனைத்து மாநிலங்கள்",
    allAccreditations: "அனைத்து அங்கீகாரங்கள்",
    accreditedScopes: "அங்கீகரிக்கப்பட்ட சோதனை எல்லைகள்",
    turnaround: "சோதனை காலம்:",
    bookSlotAi: "AI மூலம் முன்பதிவு",
    nablIsoCert: "NABL ISO/IEC 17025 சான்றளிக்கப்பட்டது",
    bookSlotBtn: "சோதனை முன்பதிவு",
    viewLabDetailsBtn: "ஆய்வக விவரம்",
    nablAccreditedBadge: "NABL அங்கீகரிக்கப்பட்டது",

    icsTechnicalSchema: "ICS தொழில்நுட்ப திட்டம்",
    enforcementDate: "நடைமுறை தேதி",
    regulatoryBody: "ஒழுங்குமுறை அமைப்பு",
    testingFacilities: "சோதனை வசதிகள்",
    keyMandatoryClauses: "கட்டாய உட்பிரிவுகள் & சோதனை நெறிமுறைகள்",
    applicableSchemeGuidance: "திட்ட வழிகாட்டுதல்",
    viewFullGazetteNotice: "அரசிதழ் அறிவிப்பைப் பார்க்கவும்",
    consultAiAssistant: "AI உதவியாளரைக் கலந்தாலோசிக்கவும்",

    demoBannerPrefix: "டெமோ பயன்முறை:",
    demoBannerSuffix: "வினவல்கள் மீதமுள்ளன. முழு அணுகலுக்கு உள்நுழையவும்.",
    loginToUnlock: "அணுகலை திறக்க உள்நுழைக",
    sessionTitle: "தரநிலை விசாரணை அமர்வு",
    strictMode: "கடுமையான பயன்முறை",
    auditTrail: "தணிக்கை பதிவு",
    gazetteSynced: "அரசிதழ் இணைக்கப்பட்டது",
    applicableStandard: "பொருந்தக்கூடிய தேசிய தரநிலை",
    mandatoryProtocols: "கட்டாய சோதனை நெறிமுறைகள்",
    recommendedNextStep: "பரிந்துரைக்கப்பட்ட அடுத்த படி",
    copyResponse: "பதிலை நகலெடு",
    copied: "நகலெடுக்கப்பட்டது",
    saveToDossier: "சேமிக்கவும்",
    exportPdf: "PDF ஏற்றுமதி",
    helpfulPrompt: "பயனுள்ளதா?",
    askPlaceholder: "மாதிரி அளவு அல்லது ஆய்வக கட்டணங்கள் பற்றி கேட்கவும்...",
    sendBtn: "அனுப்பு",
    retrievingBtn: "பெறுகிறது...",
    trySuggestions: "முயற்சிக்க:",
    regulatorySources: "ஒழுங்குமுறை ஆதாரங்கள்",
    citedCount: "சான்றளிக்கப்பட்டது",
    viewFullGazettePdf: "முழு அரசிதழ் அறிவிப்பை காண்க (PDF)",

    telemetryTitle: "இணக்க மேட்ரிக்ஸ் டெலிமெட்ரி",
    standardRisk: "தரநிலை ஆபத்து",
    testingSpan: "சோதனை காலம்",
    passThreshold: "தேர்ச்சி வரம்பு",
    nablGrounded: "NABL ISO/IEC 17025 சோதனைகளின்படி நிறுவப்பட்டது",

    authGateway: "BIS அங்கீகார நுழைவாயில்",
    loginHeading: "BISync இல் தொடங்க விரும்புகிறீர்களா?",
    loginDesc: "முழு சட்டபூர்வ அணுகல் மற்றும் வரம்பற்ற AI வினவல்களுக்கு உள்நுழையவும்.",
    selectStakeholder: "உள்நுழைய சுயவிவரத்தைத் தேர்ந்தெடுக்கவும்:",
    preConfiguredDemo: "முன்பே கட்டமைக்கப்பட்ட விசைகள்",
    loginAs: "ஆக உள்நுழைக",

    bisActCompliant: "BIS சட்டம் 2016 இணக்கமானது",
    openSchemas: "திறந்த தொழில்நுட்ப திட்டங்கள்",
    integratedGov: "ஒருங்கிணைந்த மின் ஆளுகை",
    footerDesc: "இந்திய தரநிலைகள் விதிமுறைகளுக்கு இணங்க அதிகாரப்பூர்வ சட்டபூர்வ டிஜிட்டல் கருவி. மனக் பவன், புது தில்லி 110002.",
    statutoryDisclaimer: "சட்ட மறுப்பு",
    compliancePolicy: "இணக்கக் கொள்கை",
    auditRecords: "தணிக்கை பதிவுகள்"
  },

  TE: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "ప్రమాణాలు, సరళీకృతం",
    slogan: "జాతీయ ప్రమాణాల AI డైరెక్టివ్ ఇంజిన్",
    helpline: "జాతీయ చట్టబద్ధమైన ప్రమాణాల హెల్ప్‌లైన్: 1800-11-4000 • IST 09:00 - 17:30",
    standardsLiveStatus: "BIS ప్రమాణాల లైవ్ సింక్ // 24.8 రిపోజిటరీలు",

    home: "హోమ్",
    aiAssistant: "AI అసిస్టెంట్",
    standards: "ప్రమాణాలు",
    services: "సేవలు",
    labs: "ల్యాబ్ నెట్‌వర్క్",
    signIn: "సైన్ ఇన్",
    signOut: "సైన్ అవుట్",
    demoGuest: "అతిథి వినియోగదారు",
    aiPoweredTag: "AI ఆధారిత",

    heroTagline: "జాతీయ ప్రమాణాల AI డైరెక్టివ్ ఇంజిన్ // 24.8 రిపోజిటరీలు యాక్టివ్",
    heroTitlePrefix: "భారతీయ ప్రమాణాల కోసం మీ",
    heroTitleHighlight: "ఇంటెలిజెంట్ AI గైడ్",
    heroSubtitle: "ప్రశ్న అడగండి. సరైన ప్రమాణాన్ని కనుగొనండి. అధికారిక గెజిట్ సూచనలతో నిపుణుల మార్గదర్శకత్వం పొందండి.",
    searchPlaceholder: "భారతీయ ప్రమాణాలు లేదా ISI మార్కుల గురించి అడగండి...",
    searchButton: "వెతకండి",
    ctrlK: "Ctrl K",
    standardsIndexed: "22,418 ప్రమాణాలు",
    qcoCompliance: "QCO మ్యాట్రిక్స్",
    citationEngine: "సైటేషన్ ఇంజిన్",

    domainsTitle: "మేము మీకు ఎలా సహాయం చేయవచ్చు?",
    domainsSubtitle: "లైసెన్సింగ్ మరియు టెస్టింగ్ సేవలను ఎంచుకోండి.",
    viewCatalog: "కేటలాగ్ చూడండి",
    viewLicensing: "లైసెన్సింగ్ మార్గాలు",
    searchLabs: "ల్యాబ్‌లను కనుగొనండి",
    verifyPurity: "స్వచ్ఛత కోడ్ ధృవీకరించండి",

    citationTag: "రియల్ టైమ్ సైటేషన్ స్ట్రీమ్",
    citationHeading: "ధృవీకరించబడిన చట్టబద్ధమైన విభాగాలు",
    citationDesc: "ప్రతి AI సమాధానం ఖచ్చితమైన ప్రమాణాల నిబంధనలు మరియు గెజిట్ నోటిఫికేషన్‌లకు అనుసంధానించబడింది.",
    launchRagBtn: "AI సెషన్ ప్రారంభించండి",

    infraTag: "జాతీయ నాణ్యతా మౌలిక సదుపాయాలు",
    infraHeading: "ప్రామాణిక ధృవీకరణ & ప్రయోగశాల వ్యవస్థ",
    infraDesc: "బ్యూరో ఆఫ్ ఇండియన్ స్టాండర్డ్స్ చట్టం కింద ఉత్పత్తి భద్రత మరియు పరీక్షా నెట్‌వర్క్.",
    viewAllServicesBtn: "అన్ని సేవలను చూడండి",

    workflowTag: "విధానం",
    workflowTitle: "విధానం: అడగండి → ధృవీకరించండి → చర్య తీసుకోండి",
    workflowDesc: "ప్రమాణాల విచారణలు మూడు దశల్లో ఖచ్చితమైన చట్టబద్ధమైన చర్యలుగా మార్చబడతాయి.",
    step1Title: "అడగండి",
    step1Desc: "ఉత్పత్తులు, HS కోడ్‌లు లేదా తప్పనిసరి QCO జాబితాల గురించి అడగండి.",
    step1Tag: "సెమాంటిక్ శోధన",
    step2Title: "ధృవీకరించండి",
    step2Desc: "ప్రమాణాల సారాంశాలు మరియు గుర్తింపు పొందిన ల్యాబ్‌ల జాబితాను తనిఖీ చేయండి.",
    step2Tag: "మూల ధృవీకరణ",
    step3Title: "చర్య తీసుకోండి",
    step3Desc: "తనిఖీ జాబితాను రూపొందించండి లేదా NABL ల్యాబ్ స్లాట్‌ను బుక్ చేయండి.",
    step3Tag: "రెగ్యులేటరీ ఇంజిన్",

    ctaTitle: "ప్రమాణాల నిల్వను సంప్రదించడానికి సిద్ధంగా ఉన్నారా?",
    ctaDesc: "అన్ని భారతీయ ప్రమాణాలలో లోతైన శోధనను ప్రారంభించండి.",
    ctaAskBtn: "BIS అసిస్టెంట్‌ని అడగండి",
    ctaExploreBtn: "22,000+ ప్రమాణాలను అన్వేషించండి",

    standardsTitle: "భారతీయ ప్రమాణాల శోధన",
    standardsSubtitle: "బ్యూరో ఆఫ్ ఇండియన్ స్టాండర్డ్స్ జారీ చేసిన అధికారిక మార్గదర్శకాలు మరియు స్పెసిఫికేషన్‌లు.",
    standardsRepoTag: "జాతీయ ప్రమాణాల రిపోజిటరీ • 22,482 యాక్టివ్ ప్రమాణాలు",
    schemeMandates: "స్కీమ్-I & తప్పనిసరి QCO ఆదేశాలు",
    specMandatoryBannerTitle: "ప్రామాణిక స్పెసిఫికేషన్‌లు మరియు తప్పనిసరి నాణ్యతా ఆదేశాలు",
    specMandatoryBannerDesc: "నిబంధనల స్థాయి అనుకూలత స్కీమాలు, గెజిట్ నోటిఫికేషన్‌లు మరియు పరీక్ష ప్రమాణాలు.",
    searchStandardsPlaceholder: "IS సంఖ్య, ఉత్పత్తి పేరు లేదా ICS కోడ్ ద్వారా శోధించండి...",
    allCategories: "అన్ని వర్గాలు",
    mandatoryQco: "తప్పనిసరి QCO",
    electronics: "ఎలక్ట్రానిక్స్ & IT",
    consumerGoods: "వినియోగ వస్తువులు",
    foodAgri: "ఆహారం & వ్యవసాయం",
    catalogResults: "కేటలాగ్ ఫలితాలు",
    records: "రికార్డులు",
    sortedBy: "క్రమబద్ధీకరించు:",
    relevance: "సంబంధితత",
    latestRevision: "తాజా సవరణ",
    mandatoryFirst: "తప్పనిసరి మొదట",
    viewStandard: "ప్రమాణాన్ని చూడండి",
    gazetteVerified: "గెజిట్ ధృవీకరించబడింది",
    enforced: "అమలు తేదీ:",
    askAiAboutStandard: "ఈ ప్రమాణం గురించి AI ని అడగండి",
    showing: "చూపిస్తోంది",
    of: "మొత్తం",
    standardsWord: "ప్రమాణాలు",
    allDisciplines: "అన్ని విభాగాలు",
    allStatuses: "అన్ని స్థితులు",
    qcoMandatoryOnly: "తప్పనిసరి QCO మాత్రమే",
    resultsFound: "ప్రమాణాలు అందుబాటులో ఉన్నాయి",
    viewClauseSpec: "స్పెసిఫికేషన్ చూడండి",
    mandatoryQcoBadge: "తప్పనిసరి QCO",
    voluntaryBadge: "ఐచ్ఛికం",
    activeStatus: "యాక్టివ్",
    reaffirmedStatus: "పునరుద్ఘాటించబడింది",
    underRevisionStatus: "సమీక్షలో ఉంది",

    servicesTitle: "BIS సేవలు",
    servicesSubtitle: "ధృవీకరణ మరియు ప్రయోగశాల సేవలపై స్పష్టమైన, అధికారిక మార్గదర్శకత్వం.",
    conformityFramework: "సమ్మతి & హామీ ఫ్రేమ్‌వర్క్",
    activeStandardSchemas: "యాక్టివ్ ప్రమాణాల స్కీమాలు",
    nablAssayingLabs: "NABL & అస్సేయింగ్ ల్యాబ్‌లు",
    schemesMandatesBanner: "స్కీమ్‌లు I - IV & CRS ఆదేశాలు",
    schemesBannerTitle: "ఉత్పత్తి ధృవీకరణ మార్గాలు",
    schemesBannerDesc: "ISI మార్క్, హాల్‌మార్కింగ్ (HUID), CRS IT రిజిస్ట్రేషన్ అధికారిక విధానాలు.",
    module01Tag: "మాడ్యూల్ 01 // తప్పనిసరి",
    module01Title: "సర్టిఫికేషన్",
    module01Subtitle: "BIS ధృవీకరణ అవసరాలను అర్థం చేసుకోండి.",
    module01Desc: "స్కీమ్-I (ISI మార్క్) మరియు CRS స్కీమ్‌లు, ఫీజు నిర్మాణాలను అన్వేషించండి.",
    exploreCertGuidance: "ధృవీకరణ మార్గదర్శకత్వం",
    module02Tag: "మాడ్యూల్ 02 // ల్యాబ్ నెట్‌వర్క్",
    module02Title: "టెస్టింగ్ ప్రయోగశాలలు",
    module02Subtitle: "సంబంధిత పరీక్ష సౌకర్యాలను కనుగొనండి.",
    module02Desc: "భారతదేశం అంతటా ధృవీకరించబడిన NABL మరియు BIS ల్యాబ్‌లను శోధించండి.",
    locateLabsBtn: "ల్యాబ్‌లను గుర్తించండి",
    interactiveRegistry: "ఇంటరాక్టివ్ రిజిస్ట్రీ",
    geographicLabIndex: "పిన్ కోడ్‌తో జియోగ్రాఫిక్ ల్యాబ్ ఇండెక్స్",
    module03Tag: "మాడ్యూల్ 03 // అస్సేయింగ్",
    module03Title: "హాల్‌మార్కింగ్",
    module03Subtitle: "హాల్‌మార్కింగ్ అవసరాలను తెలుసుకోండి.",
    module03Desc: "బంగారు ఆభరణాల కోసం 6 అంకెల HUID ప్రామాణికత తనిఖీలను నేర్చుకోండి.",
    viewHallmarkingRules: "హాల్‌మార్కింగ్ నియమాలు",
    huidVerificationTitle: "6-అంకెల కోడ్ ధృవీకరణ",
    verifyBtn: "ధృవీకరించండి",
    module04Tag: "మాడ్యూల్ 04 // పబ్లిక్ ఆడిట్",
    module04Title: "వినియోగదారుల సహాయం",
    module04Subtitle: "సాధారణ వినియోగదారు ప్రశ్నలకు సమాధానాలు పొందండి.",
    module04Desc: "ISI లైసెన్స్‌లను ధృవీకరించండి మరియు నకిలీ మార్కులపై ఫిర్యాదు చేయండి.",
    accessConsumerPortal: "వినియోగదారు పోర్టల్",
    licenseValidityStatus: "లైసెన్స్ స్థితి",
    instantVerification: "తక్షణ ధృవీకరణ",
    spuriousMark: "నకిలీ మార్కు ఫిర్యాదు",
    priorityDispatch: "ప్రాధాన్యత పరిష్కారం",
    autoStandardsRouting: "ఆటోమేటెడ్ స్టాండర్డ్స్ రౌటింగ్",
    autoStandardsDesc: "సేవను ఎంచుకోవడంలో సహాయం కావాలా? BIS అసిస్టెంట్‌ని అడగండి.",
    launchAiAssistant: "AI అసిస్టెంట్‌ని ప్రారంభించండి",

    labsTitle: "గుర్తింపు పొందిన పరీక్షా ప్రయోగశాలలు",
    labsSubtitle: "నమూనా మూల్యాంకనం కోసం NABL మరియు BIS గుర్తింపు పొందిన ల్యాబ్‌లను కనుగొనండి.",
    geoIntel: "జియో-ఇంటెలిజెన్స్ // 1,840 గుర్తింపు పొందిన ల్యాబ్‌లు",
    statutoryTestingEco: "చట్టబద్ధమైన పరీక్షా పర్యావరణ వ్యవస్థ",
    labBannerTitle: "జాతీయ ల్యాబ్ & కన్ఫర్మిటీ టెస్టింగ్ నెట్‌వర్క్",
    labBannerDesc: "భారతదేశం అంతటా ISO/IEC 17025 సర్టిఫైడ్ ల్యాబ్‌లు.",
    searchLabsPlaceholder: "నగరం, పేరు లేదా ప్రమాణం ద్వారా శోధించండి...",
    enterPincode: "6-అంకెల పిన్ కోడ్ నమోదు చేయండి...",
    allStandardsScope: "అన్ని ప్రమాణాల పరిధి",
    allStatesRegions: "అన్ని రాష్ట్రాలు & ప్రాంతాలు",
    allStates: "అన్ని రాష్ట్రాలు",
    allAccreditations: "అన్ని అక్రిడిటేషన్‌లు",
    accreditedScopes: "గుర్తింపు పొందిన పరీక్షా పరిధులు",
    turnaround: "పరీక్షా వ్యవధి:",
    bookSlotAi: "AI ద్వారా బుక్ చేయండి",
    nablIsoCert: "NABL ISO/IEC 17025 ధృవీకరించబడింది",
    bookSlotBtn: "టెస్టింగ్ స్లాట్ బుక్ చేయండి",
    viewLabDetailsBtn: "ల్యాబ్ వివరాలు",
    nablAccreditedBadge: "NABL గుర్తింపు పొందింది",

    icsTechnicalSchema: "ICS సాంకేతిక స్కీమా",
    enforcementDate: "అమలు తేదీ",
    regulatoryBody: "రెగ్యులేటరీ బాడీ",
    testingFacilities: "పరీక్షా సౌకర్యాలు",
    keyMandatoryClauses: "ముఖ్యమైన నిబంధనలు & పరీక్షా ప్రోటోకాల్‌లు",
    applicableSchemeGuidance: "పథకం మార్గదర్శకత్వం",
    viewFullGazetteNotice: "పూర్తి గెజిట్ నోటీసు చూడండి",
    consultAiAssistant: "AI అసిస్టెంట్‌ని సంప్రదించండి",

    demoBannerPrefix: "పరిమిత డెమో మోడ్:",
    demoBannerSuffix: "ప్రశ్నలు మిగిలి ఉన్నాయి. పూర్తి ప్రాప్యత కోసం లాగిన్ అవ్వండి.",
    loginToUnlock: "అన్‌లాక్ చేయడానికి లాగిన్ అవ్వండి",
    sessionTitle: "స్టాండర్డ్ విచారణ సెషన్",
    strictMode: "ఖచ్చితమైన మోడ్",
    auditTrail: "ఆడిట్ ట్రయిల్",
    gazetteSynced: "గెజిట్ సమకాలీకరించబడింది",
    applicableStandard: "వర్తించే జాతీయ ప్రమాణం",
    mandatoryProtocols: "తప్పనిసరి పరీక్షా ప్రోటోకాల్‌లు",
    recommendedNextStep: "సిఫార్సు చేయబడిన తదుపరి దశ",
    copyResponse: "సమాధానం కాపీ చేయండి",
    copied: "కాపీ చేయబడింది",
    saveToDossier: "సేవ్ చేయండి",
    exportPdf: "PDF డౌన్‌లోడ్",
    helpfulPrompt: "సహాయకరంగా ఉందా?",
    askPlaceholder: "నమూనా పరిమాణం లేదా ల్యాబ్ ఛార్జీల గురించి అడగండి...",
    sendBtn: "పంపండి",
    retrievingBtn: "తీసుకువస్తోంది...",
    trySuggestions: "ప్రయత్నించండి:",
    regulatorySources: "రెగ్యులేటరీ వనరులు",
    citedCount: "ఉదహరించబడింది",
    viewFullGazettePdf: "పూర్తి గెజిట్ నోటీసు చూడండి (PDF)",

    telemetryTitle: "కంప్లైయన్స్ మ్యాట్రిక్స్ టెలిమెట్రీ",
    standardRisk: "ప్రమాణాల ప్రమాదం",
    testingSpan: "పరీక్షా వ్యవధి",
    passThreshold: "ఉత్తీర్ణత పరిమితి",
    nablGrounded: "NABL ISO/IEC 17025 ప్రమాణాల ఆధారంగా నిర్ధారించబడింది",

    authGateway: "BIS అధికారిక ప్రమాణీకరణ గేట్‌వే",
    loginHeading: "మీరు BISync ప్రారంభించాలనుకుంటున్నారా?",
    loginDesc: "పూర్తి ప్రాప్యత మరియు అపరిమిత AI ప్రశ్నల కోసం లాగిన్ అవ్వండి.",
    selectStakeholder: "లాగిన్ చేయడానికి ప్రొఫైల్ ఎంచుకోండి:",
    preConfiguredDemo: "ముందుగా కాన్ఫిగర్ చేసిన కీలు",
    loginAs: "గా లాగిన్ అవ్వండి",

    bisActCompliant: "BIS చట్టం 2016 కంప్లైంట్",
    openSchemas: "ఓపెన్ టెక్నికల్ స్కీమాలు",
    integratedGov: "సమీకృత ఇ-గవర్నెన్స్",
    footerDesc: "భారతీయ ప్రమాణాల నిబంధనల ప్రకారం అధికారిక చట్టబద్ధమైన డిజిటల్ సాధనం. మానక్ భవన్, న్యూ ఢిల్లీ 110002.",
    statutoryDisclaimer: "చట్టబద్ధమైన నిరాకరణ",
    compliancePolicy: "సమ్మతి విధానం",
    auditRecords: "ఆడిట్ రికార్డులు"
  },

  MR: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "मानके, सिंक, सुलभ",
    slogan: "राष्ट्रीय मानके AI निर्देशक प्रणाली",
    helpline: "राष्ट्रीय वैधानिक मानके हेल्पलाइन: 1800-11-4000 (टोल फ्री) • वेळ 09:00 - 17:30",
    standardsLiveStatus: "BIS मानके थेट सिंक // 24.8 डेटाबेस सक्रिय",

    home: "मुख्यपृष्ठ",
    aiAssistant: "AI सहाय्यक",
    standards: "मानके शोध",
    services: "सेवा",
    labs: "प्रयोगशाळा नेटवर्क",
    signIn: "साइन इन",
    signOut: "साइन आउट",
    demoGuest: "अतिथी वापरकर्ता",
    aiPoweredTag: "AI समर्थित",

    heroTagline: "राष्ट्रीय मानके AI निर्देशक प्रणाली // 24.8 डेटाबेस सक्रिय",
    heroTitlePrefix: "भारतीय मानकांसाठी आपले",
    heroTitleHighlight: "स्मार्ट AI मार्गदर्शक",
    heroSubtitle: "प्रश्न विचारा. योग्य मानक शोधा आणि अधिकृत राजपत्र संदर्भांसह खात्रीशीर मार्गदर्शन मिळवा.",
    searchPlaceholder: "भारतीय मानके किंवा ISI चिन्हांबद्दल विचारा...",
    searchButton: "शोधा",
    ctrlK: "Ctrl K",
    standardsIndexed: "२२,४१८ मानके",
    qcoCompliance: "QCO अनुपालन",
    citationEngine: "संदर्भ प्रणाली",

    domainsTitle: "आम्ही तुम्हाला कशी मदत करू शकतो?",
    domainsSubtitle: "प्रमाणीकरण आणि चाचणी सुविधांची माहिती मिळवा.",
    viewCatalog: "कॅटलॉग पहा",
    viewLicensing: "परवाना मार्ग",
    searchLabs: "प्रयोगशाळा शोधा",
    verifyPurity: "हॉलमार्क तपासा",

    citationTag: "थेट संदर्भ प्रवाह",
    citationHeading: "सत्यापित थेट वैधानिक परिच्छेद",
    citationDesc: "प्रत्येक AI उत्तर अचूक मानक कलमे आणि अधिकृत गॅझेट अधिसूचनांशी जोडलेले असते.",
    launchRagBtn: "AI सत्र सुरू करा",

    infraTag: "राष्ट्रीय गुणवत्ता पायाभूत सुविधा",
    infraHeading: "अधिकृत प्रमाणीकरण आणि प्रयोगशाळा नेटवर्क",
    infraDesc: "भारतीय मानक ब्युरो कायद्यांतर्गत उत्पादन सुरक्षितता आणि मान्यताप्राप्त चाचणी नेटवर्क.",
    viewAllServicesBtn: "सर्व सेवा पहा",

    workflowTag: "कार्यपद्धती",
    workflowTitle: "प्रक्रिया: विचारा → तपासा → कृती करा",
    workflowDesc: "अभियांत्रिकी मानकांचे प्रश्न तीन टप्प्यांत थेट वैधानिक कृतीत रूपांतरित केले जातात.",
    step1Title: "विचारा",
    step1Desc: "उत्पादने, HS कोड किंवा अनिवार्य QCO यादीबद्दल प्रश्न विचारा.",
    step1Tag: "अर्थपूर्ण शोध",
    step2Title: "तपासा",
    step2Desc: "मानक संदर्भ आणि मान्यताप्राप्त प्रयोगशाळांची यादी तपासा.",
    step2Tag: "संदर्भ पडताळणी",
    step3Title: "कृती करा",
    step3Desc: "चेकलिस्ट तयार करा किंवा NABL प्रयोगशाळा स्लॉट बुक करा.",
    step3Tag: "वैधानिक कृती इंजिन",

    ctaTitle: "मानक डेटाबेस वापरण्यास तयार आहात?",
    ctaDesc: "सर्व भारतीय मानकांवर सखोल शोध सुरू करा.",
    ctaAskBtn: "BIS सहाय्यकाला विचारा",
    ctaExploreBtn: "सर्व २२,०००+ मानके एक्सप्लोर करा",

    standardsTitle: "भारतीय मानके शोध",
    standardsSubtitle: "भारतीय मानक ब्युरोने जारी केलेली अधिकृत मार्गदर्शक तत्त्वे आणि विनिर्देश.",
    standardsRepoTag: "राष्ट्रीय मानके डेटाबेस • २२,४८२ सक्रिय मानके",
    schemeMandates: "योजना-I आणि अनिवार्य QCO आदेश",
    specMandatoryBannerTitle: "मानक विनिर्देश आणि अनिवार्य गुणवत्ता आदेश",
    specMandatoryBannerDesc: "कलम-स्तरीय अनुपालन स्कीमा, गॅझेट अधिसूचना आणि चाचणी निकष.",
    searchStandardsPlaceholder: "IS क्रमांक, उत्पादनाचे नाव किंवा ICS कोडद्वारे शोधा...",
    allCategories: "सर्व श्रेणी",
    mandatoryQco: "अनिवार्य QCO",
    electronics: "इलेक्ट्रॉनिक्स आणि आयटी",
    consumerGoods: "ग्राहक उत्पादने",
    foodAgri: "अन्न आणि कृषी",
    catalogResults: "कॅटलॉग परिणाम",
    records: "नोंदी",
    sortedBy: "क्रमवारी लावा:",
    relevance: "सुसंगतता",
    latestRevision: "नवीनतम पुनरावृत्ती",
    mandatoryFirst: "अनिवार्य प्रथम",
    viewStandard: "मानक पहा",
    gazetteVerified: "गॅझेट सत्यापित",
    enforced: "लागू तारीख:",
    askAiAboutStandard: "या मानकाबद्दल AI ला विचारा",
    showing: "दर्शवित आहे",
    of: "पैकी",
    standardsWord: "मानके",
    allDisciplines: "सर्व तांत्रिक विभाग",
    allStatuses: "सर्व स्थिती",
    qcoMandatoryOnly: "केवळ अनिवार्य QCO",
    resultsFound: "मानके उपलब्ध",
    viewClauseSpec: "तपशील पहा",
    mandatoryQcoBadge: "अनिवार्य QCO",
    voluntaryBadge: "ऐच्छिक",
    activeStatus: "सक्रिय",
    reaffirmedStatus: "पुनःपुष्टी",
    underRevisionStatus: "पुनरावलोकनाधीन",

    servicesTitle: "BIS सेवा",
    servicesSubtitle: "अनुरूपता मूल्यमापन, चाचणी आणि ग्राहक मानकांवर अधिकृत मार्गदर्शन.",
    conformityFramework: "अनुरूपता आणि हमी फ्रेमवर्क",
    activeStandardSchemas: "सक्रिय मानक स्कीमा",
    nablAssayingLabs: "NABL आणि परख प्रयोगशाळा",
    schemesMandatesBanner: "योजना I - IV आणि CRS आदेश",
    schemesBannerTitle: "उत्पादन प्रमाणीकरण मार्ग",
    schemesBannerDesc: "ISI मार्क, हॉलमार्किंग (HUID), CRS आयटी नोंदणीसाठी वैधानिक प्रक्रिया.",
    module01Tag: "मॉड्यूल ०१ // अनिवार्य",
    module01Title: "प्रमाणीकरण",
    module01Subtitle: "BIS प्रमाणीकरण आवश्यकता समजून घ्या.",
    module01Desc: "योजना-I (ISI मार्क) आणि CRS योजना, अर्ज प्रक्रिया आणि शुल्क संरचना जाणून घ्या.",
    exploreCertGuidance: "प्रमाणीकरण मार्गदर्शन",
    module02Tag: "मॉड्यूल ०२ // प्रयोगशाळा नेटवर्क",
    module02Title: "चाचणी प्रयोगशाळा",
    module02Subtitle: "संबंधित चाचणी सुविधा शोधा.",
    module02Desc: "उत्पादन मानके आणि स्थानानुसार NABL आणि BIS मान्यताप्राप्त प्रयोगशाळा शोधा.",
    locateLabsBtn: "प्रयोगशाळा शोधा",
    interactiveRegistry: "परस्परसंवादी नोंदणी",
    geographicLabIndex: "पिन कोडसह भौगोलिक लॅब निर्देशांक",
    module03Tag: "मॉड्यूल ०३ // परख केंद्र",
    module03Title: "हॉलमार्किंग",
    module03Subtitle: "हॉलमार्किंग आवश्यकता जाणून घ्या.",
    module03Desc: "सोन्याच्या दागिन्यांसाठी ६-अंकी HUID सत्यता पडताळणी पद्धत जाणून घ्या.",
    viewHallmarkingRules: "हॉलमार्किंग नियम",
    huidVerificationTitle: "६-अंकी कोड पडताळणी",
    verifyBtn: "पडताळणी करा",
    module04Tag: "मॉड्यूल ०४ // सार्वजनिक ऑडिट",
    module04Title: "ग्राहक मदत",
    module04Subtitle: "सामान्य ग्राहक प्रश्नांची उत्तरे मिळवा.",
    module04Desc: "ISI परवाने सत्यापित करा आणि बनावट चिन्हांविरुद्ध तक्रार नोंदवा.",
    accessConsumerPortal: "ग्राहक पोर्टल",
    licenseValidityStatus: "परवाना स्थिती",
    instantVerification: "त्वरित पडताळणी",
    spuriousMark: "बनावट चिन्ह तक्रार",
    priorityDispatch: "प्राधान्य निवारण",
    autoStandardsRouting: "स्वयंचलित मानके मार्गनिर्देशन",
    autoStandardsDesc: "सेवा निवडण्यात मदत हवी आहे? BIS सहाय्यकाला विचारा.",
    launchAiAssistant: "AI सहाय्यक सुरू करा",

    labsTitle: "मान्यताप्राप्त चाचणी प्रयोगशाळा",
    labsSubtitle: "नमुना मूल्यांकनासाठी NABL आणि BIS मान्यताप्राप्त प्रयोगशाळा शोधा.",
    geoIntel: "भू-स्थानिक बुद्धिमत्ता // १,८४० मान्यताप्राप्त प्रयोगशाळा",
    statutoryTestingEco: "वैधानिक चाचणी परिसंस्था",
    labBannerTitle: "राष्ट्रीय प्रयोगशाळा आणि चाचणी नेटवर्क",
    labBannerDesc: "भारतभरात ISO/IEC 17025 प्रमाणित चाचणी केंद्रे.",
    searchLabsPlaceholder: "शहर, नाव किंवा मानकानुसार लॅब शोधा...",
    enterPincode: "६-अंकी पिन कोड टाका...",
    allStandardsScope: "सर्व मानके व्याप्ती",
    allStatesRegions: "सर्व राज्ये आणि प्रदेश",
    allStates: "सर्व राज्ये",
    allAccreditations: "सर्व मान्यता",
    accreditedScopes: "मान्यताप्राप्त चाचणी व्याप्ती",
    turnaround: "चाचणी कालावधी:",
    bookSlotAi: "AI द्वारे स्लॉट बुक करा",
    nablIsoCert: "NABL ISO/IEC 17025 प्रमाणित",
    bookSlotBtn: "चाचणी स्लॉट बुक करा",
    viewLabDetailsBtn: "तपशील पहा",
    nablAccreditedBadge: "NABL मान्यताप्राप्त",

    icsTechnicalSchema: "ICS तांत्रिक स्कीमा",
    enforcementDate: "लागू तारीख",
    regulatoryBody: "नियामक संस्था",
    testingFacilities: "चाचणी सुविधा",
    keyMandatoryClauses: "महत्त्वाचे अनिवार्य नियम आणि चाचणी प्रोटोकॉल",
    applicableSchemeGuidance: "योजना मार्गदर्शन",
    viewFullGazetteNotice: "पूर्ण गॅझेट सूचना पहा",
    consultAiAssistant: "AI सहाय्यकाचा सल्ला घ्या",

    demoBannerPrefix: "मर्यादित डेमो मोड:",
    demoBannerSuffix: "डेमो प्रश्न शिल्लक आहेत. पूर्ण प्रवेशासाठी लॉगिन करा.",
    loginToUnlock: "अनलॉक करण्यासाठी लॉगिन करा",
    sessionTitle: "मानक चौकशी सत्र",
    strictMode: "कडक मोड",
    auditTrail: "ऑडिट ट्रेल",
    gazetteSynced: "गॅझेट सिंक झाले",
    applicableStandard: "लागू राष्ट्रीय मानक",
    mandatoryProtocols: "अनिवार्य चाचणी प्रोटोकॉल",
    recommendedNextStep: "पुढील पायरी",
    copyResponse: "उत्तर कॉपी करा",
    copied: "कॉपी झाले",
    saveToDossier: "जतन करा",
    exportPdf: "PDF डाउनलोड",
    helpfulPrompt: "मदत झाली का?",
    askPlaceholder: "नमुना आकार किंवा प्रयोगशाळा शुल्काबद्दल विचारा...",
    sendBtn: "पाठवा",
    retrievingBtn: "शोधत आहे...",
    trySuggestions: "उदा.:",
    regulatorySources: "वैधानिक स्रोत",
    citedCount: "संदर्भित",
    viewFullGazettePdf: "पूर्ण गॅझेट सूचना पहा (PDF)",

    telemetryTitle: "अनुपालन विश्लेषण टेलिमेट्री",
    standardRisk: "मानक जोखीम",
    testingSpan: "चाचणी कालावधी",
    passThreshold: "उत्तीर्ण मर्यादा",
    nablGrounded: "NABL ISO/IEC 17025 निकषांवर आधारित",

    authGateway: "BIS अधिकृत प्रमाणीकरण गेटवे",
    loginHeading: "BISync सुरू करू इच्छिता?",
    loginDesc: "पूर्ण वैधानिक प्रवेश आणि अमर्यादित AI प्रश्नांसाठी लॉगिन करा.",
    selectStakeholder: "लॉगिनसाठी प्रोफाइल निवडा:",
    preConfiguredDemo: "पूर्व-कॉन्फिगर केलेल्या की",
    loginAs: "म्हणून लॉगिन करा",

    bisActCompliant: "BIS कायदा 2016 अनुपालन",
    openSchemas: "ओपन टेक्निकल स्कीमा",
    integratedGov: "एकात्मिक ई-गव्हर्नन्स",
    footerDesc: "भारतीय मानक नियमांनुसार अधिकृत वैधानिक डिजिटल साधन. मानक भवन, नवी दिल्ली 110002.",
    statutoryDisclaimer: "कायदेशीर अस्वीकरण",
    compliancePolicy: "अनुपालन धोरण",
    auditRecords: "ऑडिट नोंदी"
  },

  BN: {
    title: "BISync",
    govTag: "GOV.IN",
    subTag: "মানক, সমন্বিত, সহজ",
    slogan: "জাতীয় মানক এআই নির্দেশিকা ইঞ্জিন",
    helpline: "জাতীয় বিধিবদ্ধ মানক হেল্পলাইন: 1800-11-4000 (টোল ফ্রি) • সময় 09:00 - 17:30",
    standardsLiveStatus: "বিআইএস মানক লাইভ সিঙ্ক // ২৪.৮ রিপোজিটরি সক্রিয়",

    home: "হোম",
    aiAssistant: "এআই সহকারী",
    standards: "মানক অনুসন্ধান",
    services: "সেবাসমূহ",
    labs: "ল্যাব নেটওয়ার্ক",
    signIn: "সাইন ইন",
    signOut: "সাইন আউট",
    demoGuest: "অতিথি ব্যবহারকারী",
    aiPoweredTag: "এআই চালিত",

    heroTagline: "জাতীয় মানক এআই নির্দেশিকা ইঞ্জিন // ২৪.৮ রিপোজিটরি সক্রিয়",
    heroTitlePrefix: "ভারতীয় মানের জন্য আপনার",
    heroTitleHighlight: "স্মার্ট এআই গাইড",
    heroSubtitle: "প্রশ্ন জিজ্ঞাসা করুন। সঠিক মানক খুঁজুন এবং সরকারী গেজেট তথ্যের সাথে নির্ভরযোগ্য নির্দেশনা পান।",
    searchPlaceholder: "ভারতীয় মানক বা আইএসআই মার্ক সম্পর্কে জিজ্ঞাসা করুন...",
    searchButton: "অনুসন্ধান",
    ctrlK: "Ctrl K",
    standardsIndexed: "২২,৪১৮ মানক",
    qcoCompliance: "QCO সম্মতি",
    citationEngine: "সাইটেশন ইঞ্জিন",

    domainsTitle: "আমরা আপনাকে কীভাবে সাহায্য করতে পারি?",
    domainsSubtitle: "সার্টিফিকেশন ও পরীক্ষাগার পরিষেবা নির্বাচন করুন।",
    viewCatalog: "ক্যাটালগ দেখুন",
    viewLicensing: "লাইসেন্সিং প্রক্রিয়া",
    searchLabs: "পরীক্ষাগার খুঁজুন",
    verifyPurity: "বিশুদ্ধতা যাচাই করুন",

    citationTag: "লাইভ সাইটেশন স্ট্রীম",
    citationHeading: "যাচাইকৃত বিধিবদ্ধ ধারা",
    citationDesc: "প্রতিটি এআই উত্তর সরাসরি সুনির্দিষ্ট মানক ধারা এবং সরকারি বিজ্ঞপ্তির সাথে যুক্ত।",
    launchRagBtn: "এআই সেশন শুরু করুন",

    infraTag: "জাতীয় গুণমান পরিকাঠামো",
    infraHeading: "অনুমোদিত সার্টিফিকেশন ও ল্যাব ইকোসিস্টেম",
    infraDesc: "ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস আইনের অধীনে পণ্য সুরক্ষা ও পরীক্ষাগার নেটওয়ার্ক।",
    viewAllServicesBtn: "সকল সেবা দেখুন",

    workflowTag: "পদ্ধতি",
    workflowTitle: "প্রক্রিয়া: জিজ্ঞাসা → যাচাই → পদক্ষেপ",
    workflowDesc: "প্রকৌশল মানকের প্রশ্নগুলি তিনটি ধাপে কার্যকর বিধিবদ্ধ পদক্ষেপে রূপান্তরিত হয়।",
    step1Title: "জিজ্ঞাসা",
    step1Desc: "পণ্য, এইচএস কোড বা বাধ্যতামূলক QCO তালিকা সম্পর্কে জিজ্ঞাসা করুন।",
    step1Tag: "অর্থপূর্ণ অনুসন্ধান",
    step2Title: "যাচাই",
    step2Desc: "মানক উদ্ধৃতি এবং অনুমোদিত ল্যাব তালিকা পর্যালোচনা করুন।",
    step2Tag: "উৎস যাচাইকরণ",
    step3Title: "পদক্ষেপ",
    step3Desc: "চেকলিস্ট তৈরি করুন বা NABL ল্যাব স্লট বুক করুন।",
    step3Tag: "বিধিবদ্ধ পদক্ষেপ ইঞ্জিন",

    ctaTitle: "মানক রিপোজিটরি ব্যবহার করতে প্রস্তুত?",
    ctaDesc: "সমস্ত ভারতীয় মানক গেজেটে প্রাসঙ্গিক আইনি নির্দেশিকা সহ অনুসন্ধান করুন।",
    ctaAskBtn: "বিআইএস সহকারীকে জিজ্ঞাসা করুন",
    ctaExploreBtn: "২২,০০০+ মানক অন্বেষণ করুন",

    standardsTitle: "ভারতীয় মানক অনুসন্ধান",
    standardsSubtitle: "ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস দ্বারা জারি করা অফিসিয়াল নির্দেশিকা এবং স্পেসিফিকেশন।",
    standardsRepoTag: "জাতীয় মানক রিপোজিটরি • ২২,৪৮২ সক্রিয় মানক",
    schemeMandates: "স্কিম-১ এবং বাধ্যতামূলক QCO আদেশ",
    specMandatoryBannerTitle: "মানক স্পেসিফিকেশন এবং বাধ্যতামূলক গুণমান আদেশ",
    specMandatoryBannerDesc: "ধারা-স্তরের সম্মতি স্কিমা, গেজেট বিজ্ঞপ্তি এবং পরীক্ষার মানদণ্ড।",
    searchStandardsPlaceholder: "আইএস নম্বর, পণ্যের নাম বা আইসিএস কোড দ্বারা অনুসন্ধান করুন...",
    allCategories: "সকল বিভাগ",
    mandatoryQco: "বাধ্যতামূলক QCO",
    electronics: "ইলেকট্রনিক্স ও আইটি",
    consumerGoods: "ভোক্তা পণ্য",
    foodAgri: "খাদ্য ও কৃষি",
    catalogResults: "ক্যাটালগ ফলাফল",
    records: "রেকর্ড",
    sortedBy: "সাজান:",
    relevance: "প্রাসঙ্গিকতা",
    latestRevision: "সর্বশেষ সংশোধন",
    mandatoryFirst: "বাধ্যতামূলক আগে",
    viewStandard: "মানক দেখুন",
    gazetteVerified: "গেজেট যাচাইকৃত",
    enforced: "কার্যকর তারিখ:",
    askAiAboutStandard: "এই মানক সম্পর্কে এআই-কে জিজ্ঞাসা করুন",
    showing: "দেখানো হচ্ছে",
    of: "মোট",
    standardsWord: "মানক",
    allDisciplines: "সকল প্রযুক্তিগত বিভাগ",
    allStatuses: "সকল স্থিতি",
    qcoMandatoryOnly: "বাধ্যতামূলক QCO মাত্র",
    resultsFound: "মানক উপলব্ধ",
    viewClauseSpec: "বিবরণ দেখুন",
    mandatoryQcoBadge: "বাধ্যতামূলক QCO",
    voluntaryBadge: "স্বেচ্ছামূলক",
    activeStatus: "সক্রিয়",
    reaffirmedStatus: "পুনঃনিশ্চিত",
    underRevisionStatus: "সংশোধনাধীন",

    servicesTitle: "বিআইএস সেবাসমূহ",
    servicesSubtitle: "সার্টিফিকেশন ও পরীক্ষাগার পরিষেবাগুলির স্পষ্ট ও নির্ভরযোগ্য নির্দেশনা।",
    conformityFramework: "সম্মতি ও নিশ্চয়তা পরিকাঠামো",
    activeStandardSchemas: "সক্রিয় স্কিমা",
    nablAssayingLabs: "NABL ও যাচাইকরণ ল্যাব",
    schemesMandatesBanner: "স্কিম ১ - ৪ ও CRS আদেশ",
    schemesBannerTitle: "পণ্য সার্টিফিকেশন পথ",
    schemesBannerDesc: "আইএসআই মার্ক, হলমার্কিং (HUID), CRS আইটি নিবন্ধনের জন্য বিধিবদ্ধ প্রক্রিয়া।",
    module01Tag: "মডিউল ০১ // বাধ্যতামূলক",
    module01Title: "সার্টিফিকেশন",
    module01Subtitle: "বিআইএস সার্টিফিকেশন প্রয়োজনীয়তা বুঝুন।",
    module01Desc: "স্কিম-১ (আইএসআই মার্ক) এবং CRS স্কিম, আবেদন প্রক্রিয়া ও ফি কাঠামো অন্বেষণ করুন।",
    exploreCertGuidance: "সার্টিফিকেশন নির্দেশিকা",
    module02Tag: "মডিউল ০২ // ল্যাব নেটওয়ার্ক",
    module02Title: "পরীক্ষাগার",
    module02Subtitle: "প্রাসঙ্গিক পরীক্ষাগার খুঁজুন।",
    module02Desc: "পণ্যের মান এবং অবস্থান অনুযায়ী ভারত জুড়ে অনুমোদিত NABL ও BIS ল্যাব খুঁজুন।",
    locateLabsBtn: "পরীক্ষাগার খুঁজুন",
    interactiveRegistry: "ইন্টারেক্টিভ রেজিস্ট্রি",
    geographicLabIndex: "পিন কোড সহ ভৌগোলিক ল্যাব সূচক",
    module03Tag: "মডিউল ০৩ // যাচাইকরণ",
    module03Title: "হলমার্কিং",
    module03Subtitle: "হলমার্কিং সংক্রান্ত নিয়মাবলী জানুন।",
    module03Desc: "স্বর্ণালঙ্কারের জন্য ৬ সংখ্যার HUID সত্যতা যাচাই প্রক্রিয়া জানুন।",
    viewHallmarkingRules: "হলমার্কিং নিয়ম",
    huidVerificationTitle: "৬ সংখ্যার কোড যাচাইকরণ",
    verifyBtn: "যাচাই করুন",
    module04Tag: "মডিউল ০৪ // গণ নিরীক্ষা",
    module04Title: "ভোক্তা সহায়তা",
    module04Subtitle: "সাধারণ ভোক্তা প্রশ্নের উত্তর পান।",
    module04Desc: "আইএসআই লাইসেন্স যাচাই করুন এবং নকল চিহ্নের বিরুদ্ধে অভিযোগ নথিভুক্ত করুন।",
    accessConsumerPortal: "ভোক্তা পোর্টাল",
    licenseValidityStatus: "লাইসেন্সের স্থিতি",
    instantVerification: "তাৎক্ষণিক যাচাইকরণ",
    spuriousMark: "নকল চিহ্ন অভিযোগ",
    priorityDispatch: "অগ্রাধিকার সমাধান",
    autoStandardsRouting: "স্বয়ংক্রিয় মানক রাউটিং",
    autoStandardsDesc: "পরিষেবা বেছে নিতে সাহায্য প্রয়োজন? বিআইএস সহকারীকে জিজ্ঞাসা করুন।",
    launchAiAssistant: "এআই সহকারী শুরু করুন",

    labsTitle: "স্বীকৃত পরীক্ষাগার",
    labsSubtitle: "নমুনা মূল্যায়নের জন্য NABL এবং BIS অনুমোদিত পরীক্ষাগার খুঁজুন।",
    geoIntel: "ভৌগোলিক তথ্য // ১,৮৪০ অনুমোদিত পরীক্ষাগার",
    statutoryTestingEco: "বিধিবদ্ধ পরীক্ষা ইকোসিস্টেম",
    labBannerTitle: "জাতীয় ল্যাব এবং পরীক্ষা নেটওয়ার্ক",
    labBannerDesc: "ভারত জুড়ে ISO/IEC 17025 প্রত্যয়িত ল্যাব।",
    searchLabsPlaceholder: "শহর, নাম বা মানক দ্বারা ল্যাব খুঁজুন...",
    enterPincode: "৬ সংখ্যার পিন কোড লিখুন...",
    allStandardsScope: "সকল মানক ক্ষেত্র",
    allStatesRegions: "সকল রাজ্য ও অঞ্চল",
    allStates: "সকল রাজ্য",
    allAccreditations: "সকল স্বীকৃতি",
    accreditedScopes: "স্বীকৃত পরীক্ষার ক্ষেত্র",
    turnaround: "পরীক্ষার সময়কাল:",
    bookSlotAi: "এআই দ্বারা বুক করুন",
    nablIsoCert: "NABL ISO/IEC 17025 প্রত্যয়িত",
    bookSlotBtn: "ল্যাব স্লট বুক করুন",
    viewLabDetailsBtn: "বিবরণ দেখুন",
    nablAccreditedBadge: "NABL অনুমোদিত",

    icsTechnicalSchema: "ICS প্রযুক্তিগত স্কিমা",
    enforcementDate: "কার্যকর তারিখ",
    regulatoryBody: "নিয়ামক সংস্থা",
    testingFacilities: "পরীক্ষা সুবিধা",
    keyMandatoryClauses: "বাধ্যতামূলক ধারা ও পরীক্ষার প্রোটোকল",
    applicableSchemeGuidance: "স্কিম নির্দেশিকা",
    viewFullGazetteNotice: "সম্পূর্ণ গেজেট বিজ্ঞপ্তি দেখুন",
    consultAiAssistant: "এআই সহকারীর পরামর্শ নিন",

    demoBannerPrefix: "সীমিত ডেমো মোড:",
    demoBannerSuffix: "প্রশ্ন অবশিষ্ট আছে। সম্পূর্ণ অ্যাক্সেসের জন্য লগইন করুন।",
    loginToUnlock: "আনলক করতে লগইন করুন",
    sessionTitle: "মানক অনুসন্ধান অধিবেশন",
    strictMode: "কঠোর মোড",
    auditTrail: "অডিট ট্রেইল",
    gazetteSynced: "গেজেট সিঙ্ক হয়েছে",
    applicableStandard: "প্রযোজ্য জাতীয় মানক",
    mandatoryProtocols: "বাধ্যতামূলক পরীক্ষার প্রোটোকল",
    recommendedNextStep: "প্রস্তাবিত পরবর্তী পদক্ষেপ",
    copyResponse: "উত্তর কপি করুন",
    copied: "কপি হয়েছে",
    saveToDossier: "সংরক্ষণ করুন",
    exportPdf: "PDF ডাউনলোড",
    helpfulPrompt: "সহায়ক ছিল?",
    askPlaceholder: "নমুনার আকার বা ল্যাব ফি সম্পর্কে জিজ্ঞাসা করুন...",
    sendBtn: "পাঠান",
    retrievingBtn: "অনুসন্ধান চলছে...",
    trySuggestions: "পরামর্শ:",
    regulatorySources: "বিধিবদ্ধ উৎস",
    citedCount: "উদ্ধৃত",
    viewFullGazettePdf: "সম্পূর্ণ গেজেট বিজ্ঞপ্তি দেখুন (PDF)",

    telemetryTitle: "সম্মতি বিশ্লেষণ টেলিমেট্রি",
    standardRisk: "মানক ঝুঁকি",
    testingSpan: "পরীক্ষার সময়কাল",
    passThreshold: "উত্তীর্ণের সীমা",
    nablGrounded: "NABL ISO/IEC 17025 পরীক্ষার ভিত্তিতে যাচাইকৃত",

    authGateway: "বিআইএস অফিসিয়াল প্রমাণীকরণ গেটওয়ে",
    loginHeading: "আপনি কি BISync শুরু করতে চান?",
    loginDesc: "সম্পূর্ণ অ্যাক্সেস ও সীমাহীন এআই প্রশ্নের জন্য লগইন করুন।",
    selectStakeholder: "লগইন করতে প্রোফাইল নির্বাচন করুন:",
    preConfiguredDemo: "প্রাক-কনফিগার করা কী",
    loginAs: "হিসাবে লগইন করুন",

    bisActCompliant: "বিআইএস আইন ২০১৬ অনুগত",
    openSchemas: "ওপেন টেকনিক্যাল স্কিমা",
    integratedGov: "সমন্বিত ই-গভর্ন্যান্স",
    footerDesc: "ভারতীয় মানক নিয়মাবলী অনুযায়ী অফিসিয়াল বিধিবদ্ধ ডিজিটাল মাধ্যম। মানক ভবন, নয়াদিল্লি ১১০০০২।",
    statutoryDisclaimer: "বিধিবদ্ধ দাবিত্যাগ",
    compliancePolicy: "সম্মতি নীতি",
    auditRecords: "অডিট রেকর্ড"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');
  const t = translations[lang] || translations.EN;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
